//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef _TtC10XCTestCore19XCTReportingContext_h
#define _TtC10XCTestCore19XCTReportingContext_h
@import Foundation;
@import UIKit;

@class NSObject;

@interface XCTReportingContext : NSObject { // (Swift)
    /* instance variables */
     id ideProxy;
     id configuration;
     id publisher;
}

/* instance methods */
- (id)init;

@end

#endif /* _TtC10XCTestCore19XCTReportingContext_h */
