//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef _XCTestObservationPrivate_Protocol_h
#define _XCTestObservationPrivate_Protocol_h
#import <XCTest/XCTestObservation.h>
@import Foundation;
@import UIKit;


@protocol _XCTestObservationPrivate <XCTestObservation>

@required

@optional

/* optional instance methods */
- (void)_context:(id)_context willStartActivity:(id)activity;
- (void)_context:(id)_context didFinishActivity:(id)activity;
- (void)testCase:(id)_case didRecordSkipWithDescription:(id)description sourceCodeContext:(id)context;

@end

#endif /* _XCTestObservationPrivate_Protocol_h */
