//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef _XCTestObservationInternal_Protocol_h
#define _XCTestObservationInternal_Protocol_h
@import Foundation;
@import UIKit;

#include "_XCTestObservationPrivate-Protocol.h"

@protocol _XCTestObservationInternal <_XCTestObservationPrivate>

@required

@optional

/* optional instance methods */
- (void)testSuite:(id)suite didRecordSkipWithDescription:(id)description sourceCodeContext:(id)context;
- (void)testCasePlaceholder:(id)placeholder isUnavailableWithReason:(id)reason;

@end

#endif /* _XCTestObservationInternal_Protocol_h */
