//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef NSFastEnumeration_Protocol_h
#define NSFastEnumeration_Protocol_h
@import Foundation;
@import UIKit;

@protocol NSFastEnumeration

@required

/* required instance methods */
- (unsigned long long)countByEnumeratingWithState:(struct { unsigned long long x0; id *x1; unsigned long long *x2; unsigned long long x3[5]; } *)state objects:(id *)objects count:(unsigned long long)count;

@optional

@end

#endif /* NSFastEnumeration_Protocol_h */
