//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCApplicationQuery_h
#define XCApplicationQuery_h
@import Foundation;
@import UIKit;

#include "XCUIElementQuery.h"

@class XCElementSnapshot, XCUIApplication, XCUIElementQuery;

@interface XCApplicationQuery : XCUIElementQuery {
    /* instance variables */
    XCUIApplication *_application;
}

@property (retain) id/*XCElementSnapshot*/ lastSnapshot;

/* instance methods */
- (void)dealloc;
- (id)initWithApplication:(id)application;
- (id)application;

@end

#endif /* XCApplicationQuery_h */
