//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCAXClient_iOS_h
#define XCAXClient_iOS_h
@import Foundation;
@import UIKit;

#include "XCUIAccessibilityInterface-Protocol.h"
#include "XCUIApplicationProcessTracker-Protocol.h"
#include "XCUIRemoteAccessibilityInterface-Protocol.h"

@class NSArray, NSMutableDictionary, NSObject, NSString, XCAccessibilityElement, XCUIDevice;
@protocol OS_dispatch_queue, XCUIDevice;

@interface XCAXClient_iOS : NSObject <XCUIAccessibilityInterface>

@property (retain) NSObject<OS_dispatch_queue> *queue;
@property (readonly) id <XCUIApplicationProcessTracker> applicationProcessTracker;
@property (readonly) id <XCUIRemoteAccessibilityInterface> remoteAccessibilityInterface;
@property (readonly) NSMutableDictionary *userTestingNotificationHandlers;
@property (readonly) NSMutableDictionary *oneShotUserTestingNotificationHandlers;
@property (readonly) NSMutableDictionary *cachedAccessibilityLoadedValuesForPIDs;
@property (readonly) _Bool cachedSystemAppIsLoadedNotificationValue;
@property (readonly, weak) id <XCUIDevice> device;
@property double AXTimeout;
@property (readonly) _Bool supportsAnimationsInactiveNotifications;
@property (readonly) NSArray *activeForegroundApplications;
@property (readonly, nonatomic) XCAccessibilityElement *systemApplication;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) _Bool axNotificationsIncludeElement;
@property (readonly) _Bool allowsRemoteAccess;
@property (readonly) _Bool supportsHostedViewCoordinateTransformations;
@property (readonly) _Bool usePointTransformationsForFrameConversions;
@property (readonly) _Bool hasBannerNotificationIsStickyAttribute;
@property (readonly) _Bool providesValuesForPrivilegedAttributes;

/* instance methods */
- (id)initWithApplicationProcessTracker:(id)tracker remoteAccessibilityInterface:(id)interface device:(id)device;
- (_Bool)_loadAccessibility:(id *)accessibility;
- (_Bool)_unloadAccessibility:(id *)accessibility;
- (_Bool)_registerForAXNotification:(int)axnotification error:(id *)error;
- (_Bool)isAccessibilitySupported;
- (_Bool)loadAccessibility:(id *)accessibility;
- (_Bool)unloadAccessibility:(id *)accessibility;
- (_Bool)isValidElement:(id)element;
- (_Bool)enableFauxCollectionViewCells:(id *)cells;
- (id)activeApplications;
- (_Bool)cachedAccessibilityLoadedValueForPID:(int)pid;
- (_Bool)cachedSystemAppIsLoaded;
- (id)hitTestElement:(id)element withPoint:(CGPoint)point error:(id *)error;
- (void)_handleUserTestingNotificationFromElement:(id)element withPayload:(id)payload;
- (id)_addUserTestNotificationHandler:(id /* block */)handler;
- (void)_removeUserTestNotificationHandlerForToken:(id)token;
- (void)notifyOnNextOccurrenceOfUserTestingEvent:(id)event handler:(id /* block */)handler;
- (void)handleAccessibilityNotification:(int)notification fromElement:(id)element payload:(id)payload;
- (_Bool)isMacCatalystForPID:(int)pid;
- (void)waitForQuiescenceOnAllForegroundApplicationsAsPreEvent:(_Bool)event;
- (id)_activeForegroundApplicationsWithPotentiallyInterruptingUI;
- (id)_hittableElementsInSnapshots:(id)snapshots;
- (id)_snapshotsForInterruptingElementsPresentedByApplication:(id)application interuptedSnapshotFrame:(CGRect)frame;
- (void)notifyWhenEventLoopIsIdleForApplication:(id)application reply:(id /* block */)reply;
- (void)notifyWhenNoAnimationsAreActiveForApplication:(id)application reply:(id /* block */)reply;
- (id)viewDidAppearExpectationForElement:(id)element viewControllerName:(id)name;
- (void)notifyWhenViewControllerViewDidDisappearReply:(id /* block */)reply;
- (id)defaultParameters;
- (id)runAccessibilityAuditForApplication:(id)application withConfiguration:(id)configuration error:(id *)error;
- (id)requestSnapshotForElement:(id)element attributes:(id)attributes parameters:(id)parameters error:(id *)error;
- (id)attributesForElement:(id)element attributes:(id)attributes error:(id *)error;
- (id)valuesForPrivilegedAttributes:(id)attributes forElement:(id)element error:(id *)error;
- (_Bool)setAttribute:(id)attribute value:(id)value element:(id)element outError:(id *)error;
- (id)parameterizedAttribute:(id)attribute forElement:(id)element parameter:(id)parameter error:(id *)error;
- (_Bool)performAction:(id)action onElement:(id)element value:(id)value error:(id *)error;
- (id)localizableStringsDataForActiveApplications;
- (_Bool)_setAXTimeout:(double)axtimeout error:(id *)error;
- (void)registerForAXNotificationsForApplicationWithPID:(int)pid timeout:(double)timeout completion:(id /* block */)completion;
- (void)unregisterForAXNotificationsForApplicationWithPID:(int)pid;
- (id)addObserverForAXNotification:(id)axnotification handler:(id /* block */)handler;
- (void)removeObserver:(id)observer forAXNotification:(id)axnotification;
- (void)performWhenMenuOpens:(id)opens block:(id /* block */)block;
- (id)accessibilityElementForElementAtPoint:(CGPoint)point error:(id *)error;
- (void)handleAccessibilityNotification:(id)notification element:(id)element userInfo:(id)info;

@end

#endif /* XCAXClient_iOS_h */
