//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCPointerEventPath_h
#define XCPointerEventPath_h
@import Foundation;
@import UIKit;

@class NSArray, NSData, NSMutableArray, NSObject;

@interface XCPointerEventPath : NSObject <NSSecureCoding>

@property _Bool immutable;
@property unsigned long long index;
@property unsigned long long deviceID;
@property (readonly) unsigned long long pathType;
@property (readonly) CGPoint initialMouseLocation;
@property (readonly) NSArray *pointerEvents;
@property (readonly) double maximumOffset;
@property (readonly) NSData *eventStream;
@property (readonly) CGRect targetFrame;
@property (readonly) double speedFactor;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initForTouchAtPoint:(CGPoint)point offset:(double)offset;
- (id)initForMouseEvents;
- (id)initForMouseEventsAtLocation:(CGPoint)location;
- (id)initForMouseEventsWithDeviceID:(unsigned long long)id atLocation:(CGPoint)location;
- (id)initForTextInput;
- (id)initForTouchBarAtPoint:(CGPoint)point offset:(double)offset;
- (id)initForEventStream:(id)stream frame:(CGRect)frame speed:(double)speed;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (void)pressDownAtOffset:(double)offset;
- (void)pressDownWithPressure:(double)pressure atOffset:(double)offset;
- (void)pressDownWithPressure:(double)pressure stage:(unsigned long long)stage phase:(unsigned long long)phase atOffset:(double)offset;
- (void)moveToPoint:(CGPoint)point atOffset:(double)offset;
- (void)moveMouseToPoint:(CGPoint)point atOffset:(double)offset duration:(double)duration;
- (void)liftUpAtOffset:(double)offset;
- (void)pressButton:(unsigned long long)button atOffset:(double)offset clickCount:(unsigned long long)count;
- (void)dragWithButton:(unsigned long long)button toPoint:(CGPoint)point atOffset:(double)offset duration:(double)duration;
- (void)releaseButton:(unsigned long long)button atOffset:(double)offset clickCount:(unsigned long long)count;
- (void)scrollWithDeltaVector:(CGVector)vector atOffset:(double)offset duration:(double)duration;
- (void)gestureSwipeWithDeltaVector:(CGVector)vector atOffset:(double)offset duration:(double)duration;
- (void)scrollAtPoint:(CGPoint)point byLines:(long long)lines atOffset:(double)offset;
- (void)typeText:(id)text atOffset:(double)offset typingSpeed:(unsigned long long)speed shouldRedact:(_Bool)redact;
- (void)typeKey:(id)key modifiers:(unsigned long long)modifiers atOffset:(double)offset;
- (void)setModifiers:(unsigned long long)modifiers mergeWithCurrentModifierFlags:(_Bool)flags atOffset:(double)offset;
- (void)_addPointerEvent:(id)event;
- (id)firstEventAtOffset:(double)offset;
- (id)lastEventBeforeOffset:(double)offset;
- (id)firstEventAfterOffset:(double)offset;
- (id)description;

@end

#endif /* XCPointerEventPath_h */
