//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCPointerEvent_h
#define XCPointerEvent_h
@import Foundation;
@import UIKit;

@class NSObject, NSString;

@interface XCPointerEvent : NSObject <NSSecureCoding>

@property unsigned long long eventType;
@property unsigned long long buttonType;
@property CGPoint coordinate;
@property CGPoint destination;
@property double pressure;
@property unsigned long long gestureStage;
@property double offset;
@property CGVector deltaVector;
@property double duration;
@property long long verticalLineScroll;
@property unsigned long long clickCount;
@property unsigned long long keyModifierFlags;
@property _Bool mergeModifierFlagsWithCurrentFlags;
@property (copy) NSString *key;
@property (copy) NSString *string;
@property unsigned long long typingSpeed;
@property _Bool shouldRedact;
@property unsigned long long keyCode;
@property unsigned long long keyPhase;
@property unsigned long long gesturePhase;
@property unsigned long long deviceID;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)scrollEventWithDeltaVector:(CGVector)vector offset:(double)offset duration:(double)duration;
+ (id)gestureSwipeEventWithDeltaVector:(CGVector)vector offset:(double)offset duration:(double)duration phase:(unsigned long long)phase;
+ (id)scrollEventAtPoint:(CGPoint)point lines:(long long)lines offset:(double)offset;
+ (id)dragEventWithCoordinate:(CGPoint)coordinate destination:(CGPoint)destination offset:(double)offset duration:(double)duration;
+ (id)moveEventWithStartPoint:(CGPoint)point destination:(CGPoint)destination offset:(double)offset duration:(double)duration;
+ (id)textEventForModifierFlags:(unsigned long long)flags mergeWithCurrent:(_Bool)current offset:(double)offset;
+ (id)textEventForKey:(id)key withModifierFlags:(unsigned long long)flags offset:(double)offset;
+ (id)textEventForString:(id)string offset:(double)offset typingSpeed:(unsigned long long)speed;
+ (id)textEventForString:(id)string offset:(double)offset typingSpeed:(unsigned long long)speed shouldRedact:(_Bool)redact;
+ (id)keyboardEventForKeyCode:(unsigned long long)code keyPhase:(unsigned long long)phase modifierFlags:(unsigned long long)flags offset:(double)offset;
+ (id)keyboardEventForKeyCode:(unsigned long long)code keyPhase:(unsigned long long)phase modifierFlags:(unsigned long long)flags offset:(double)offset shouldRedact:(_Bool)redact;
+ (id /* block */)offsetComparator;

/* instance methods */
- (id)init;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)description;

@end

#endif /* XCPointerEvent_h */
