//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTAttachmentManager_h
#define XCTAttachmentManager_h
@import Foundation;
@import UIKit;

@class NSMutableArray, NSObject, XCTestCase;

@interface XCTAttachmentManager : NSObject

@property (readonly) NSMutableArray *attachments;
@property _Bool isValid;
@property (readonly) XCTestCase *testCase;

/* class methods */
+ (void)_synthesizeActivityForAttachment:(id)attachment testCase:(id)_case;

/* instance methods */
- (id)initWithTestCase:(id)_case;
- (void)dealloc;
- (void)_invalidate;
- (void)ensureNoRemainingAttachments;
- (void)dequeueAndReportBackgroundAttachments;
- (void)enqueueAttachment:(id)attachment;

@end

#endif /* XCTAttachmentManager_h */
