//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTAggregateSuiteRunStatistics_h
#define XCTAggregateSuiteRunStatistics_h
@import Foundation;
@import UIKit;

@class NSArray, NSDictionary, NSMutableDictionary, NSObject, NSString;

@interface XCTAggregateSuiteRunStatistics : NSObject <NSCopying, NSSecureCoding>

@property (readonly) NSMutableDictionary *recordMap;
@property (readonly) NSDictionary *dictionaryRepresentation;
@property (copy) NSString *lastTestIdentifier;
@property (readonly) unsigned long long suiteRecordCount;
@property (readonly) NSArray *suiteRecords;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)init;
- (id)initWithDictionaryRepresentation:(id)representation;
- (_Bool)isEqual:(id)equal;
- (_Bool)isEqualToStatistics:(id)statistics;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (void)addSuiteRecord:(id)record;
- (id)recordForSuiteNamed:(id)named;

@end

#endif /* XCTAggregateSuiteRunStatistics_h */
