//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTCapabilities_h
#define XCTCapabilities_h
@import Foundation;
@import UIKit;

@class NSDictionary, NSObject;

@interface XCTCapabilities : NSObject <NSSecureCoding>

@property (readonly, copy) NSDictionary *capabilitiesDictionary;
@property (readonly, copy) NSDictionary *dictionaryRepresentation;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (id)emptyCapabilities;

/* instance methods */
- (id)initWithDictionary:(id)dictionary;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)description;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (unsigned long long)versionForCapability:(id)capability;
- (_Bool)hasCapability:(id)capability;

@end

#endif /* XCTCapabilities_h */
