//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTestCaseRun_h
#define XCTestCaseRun_h
#import <XCTest/XCTestCaseRun.h>
@import Foundation;
@import UIKit;

#include "XCTestRun.h"

@class XCTestRun;

@interface XCTestCaseRun (FBXCTestPrivate)

/* instance methods */
- (void)start;
- (void)stop;
- (void)recordSkipWithDescription:(id)description sourceCodeContext:(id)context;
- (void)recordExpectedFailure:(id)failure;
- (void)_handleIssue:(id)issue;

@end

#endif /* XCTestCaseRun_h */
