//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTestCase_h
#define XCTestCase_h
#import <XCTest/XCTestCase.h>
@import Foundation;
@import UIKit;

#include "XCTMemoryCheckerDelegate-Protocol.h"
#include "XCTest.h"
#include "XCTestCaseDiscoveryUIAutomationDelegate-Protocol.h"
#include "XCTestCaseUIAutomationDelegate-Protocol.h"
#include "XCTestCastMethodNamesUIAutomationDelegate-Protocol.h"

@class MXMInstrument, NSArray, NSDictionary, NSHashTable, NSInvocation, NSMutableArray, NSMutableDictionary, NSMutableSet, NSObject, NSString, NSThread, XCTAttachmentManager, XCTIssue, XCTMemoryChecker, XCTMetricDiagnosticHelper, XCTRepetitionPolicy, XCTTestIdentifier, XCTWaiter, XCTest, XCTestCaseRun;
@protocol OS_dispatch_source;

@interface XCTestCase (FBXCTestPrivate)


@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *name;
@property (copy) XCTIssue *candidateIssueForCurrentThread;
@property long long runLoopNestingCount;
@property (copy) NSDictionary *activityAggregateStatistics;
@property (retain) XCTRepetitionPolicy *repetitionPolicyInternal;
@property (retain) NSThread *primaryThread;
@property (nonatomic) _Bool shouldHaltWhenReceivesControl;
@property (nonatomic) _Bool shouldSetShouldHaltWhenReceivesControl;
@property (nonatomic) _Bool hasAttemptedToCaptureScreenshotOnFailure;
@property (retain) XCTestCaseRun *testCaseRun;
@property (retain, nonatomic) XCTMemoryChecker *defaultMemoryChecker;
@property (readonly) struct { long long x0; long long x1; long long x2; } minimumOperatingSystemVersion;
@property (readonly) double _effectiveExecutionTimeAllowance;
@property (nonatomic) _Bool _preciseTimeoutsEnabled;
@property (retain) NSMutableDictionary *_perfMetricsForID;
@property _Bool _didMeasureMetrics;
@property _Bool _didStartMeasuring;
@property _Bool _didStopMeasuring;
@property _Bool _isAutomaticallyMeasuring;
@property unsigned long long maxDurationInMinutes;
@property (readonly) NSDictionary *testRunConfiguration;
@property (readonly) _Bool shouldRelaunchBeforeRunningTest;
@property long long retryOnFailureCount;

/* class methods */
+ (id)defaultPerformanceMetrics;
+ (id)defaultMetrics;
+ (id)defaultMeasureOptions;
+ (_Bool)_reportPerformanceFailuresForLargeImprovements;
+ (_Bool)_treatMissingBaselinesAsTestFailures;
+ (id)_baselineDictionary;
+ (id)removeDigitsFromString:(id)string;
+ (id)defaultTestSuite;
+ (id)_variationOptions;
+ (id)_allSubclasses;
+ (id)allSubclasses;
+ (id)allSubclassesOutsideXCTest;
+ (_Bool)isValidTestMethodWithSignature:(id)signature convention:(long long *)convention;
+ (id)_testMethodInvocationDescriptors;
+ (id)testMethodInvocations;
+ (void)_collectTestInvocationDescriptorsForClassHierarchyIntoDictionary:(id)dictionary;
+ (id)_allTestMethodInvocationDescriptors;
+ (id)allTestMethodInvocations;
+ (_Bool)overridesDefaultTestSuite;
+ (_Bool)overridesTestInvocations;
+ (id)testCaseWithInvocation:(id)invocation testRunConfiguration:(id)configuration;
+ (_Bool)_isDiscoverable;
+ (id)testRunConfigurationInputs;
+ (SEL)_resolvedTestMethodSelectorForSelector:(SEL)selector;
+ (id)testCaseWithSelector:(SEL)selector identifier:(id)identifier testRunConfiguration:(id)configuration;
+ (id)testCaseWithSelector:(SEL)selector testRunConfiguration:(id)configuration;
+ (id)_identifierForSelectorString:(id)string;
+ (id)_identifierForInvocation:(id)invocation;
+ (id)_languageSpecificTestMethodNameForSelector:(SEL)selector;
+ (_Bool)customizesTestMethodNameViaOverrides;
+ (_Bool)shouldSortTestsBySelector;
+ (_Bool)isInheritingTestCases;
+ (id)testInvocations;
+ (id)_testInvocationDescriptors;
+ (_Bool)_isAvailable;
+ (struct { long long x0; long long x1; long long x2; })minimumOperatingSystemVersion;

/* instance methods */
- (void)registerMetricID:(id)id name:(id)name unit:(id)unit;
- (void)registerMetricID:(id)id name:(id)name unitString:(id)string;
- (void)registerMetricID:(id)id name:(id)name unitString:(id)string polarity:(long long)polarity;
- (void)reportMeasurements:(id)measurements forMetricID:(id)id reportFailures:(_Bool)failures;
- (void)_logAndReportPerformanceMetrics:(id)metrics perfMetricResultsForIDs:(id)ids withBaselinesForTest:(id)test;
- (id)baselinesDictionaryForTest;
- (id)addAdditionalIterationsBasedOnOptions:(id)options;
- (void)reportMetric:(id)metric reportFailures:(_Bool)failures;
- (void)_logAndReportPerformanceMetrics:(id)metrics perfMetricResultsForIDs:(id)ids withBaselinesForTest:(id)test defaultBaselinesForPerfMetricID:(id)id;
- (void)_registerDefaultMetrics;
- (_Bool)_shouldAutomaticallyCollectPerformanceMetrics;
- (id)_processNamesToCollectPerformance;
- (id)_defaultAutomaticMetrics;
- (id)_defaultAutomaticMeasureOptions;
- (void)handleIssue:(id)issue;
- (void)handleIssue:(id)issue completionHandler:(id /* block */)handler;
- (id)_storageKeyForCandidateIssue;
- (void)expectFailureWithContext:(id)context;
- (_Bool)_isDuplicateOfIssue:(id)issue;
- (void)_recordIssue:(XCTIssue *)issue;
- (void)_enqueueIssue:(id)issue;
- (void)_dequeueIssues;
- (void)_handleIssue:(id)issue;
- (_Bool)_caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:(_Bool)interruptions whileExecutingBlock:(id /* block */)block;
- (_Bool)_caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:(_Bool)interruptions caughtInterruptionException:(_Bool *)exception whileExecutingBlock:(id /* block */)block;
- (void)_interruptOrMarkForLaterInterruption;
- (void)addAttachment:(id)attachment;
- (void)swift_waitForExpectations:(id)expectations timeout:(double)timeout enforceOrder:(_Bool)order completionHandler:(id /* block */)handler;
- (id)_expectationForDarwinNotification:(id)notification;
- (id)_expectationForDistributedNotification:(id)notification object:(id)object handler:(id /* block */)handler;
- (void)waitForExpectationsWithTimeout:(double)timeout handler:(id /* block */)handler;
- (void)waitForExpectations:(id)expectations;
- (void)waitForExpectations:(id)expectations timeout:(double)timeout;
- (void)waitForExpectations:(id)expectations enforceOrder:(_Bool)order;
- (void)waitForExpectations:(id)expectations timeout:(double)timeout enforceOrder:(_Bool)order;
- (id)expectationWithDescription:(id)description;
- (id)keyValueObservingExpectationForObject:(id)object keyPath:(id)path expectedValue:(id)value;
- (id)keyValueObservingExpectationForObject:(id)object keyPath:(id)path handler:(id /* block */)handler;
- (id)expectationForNotification:(id)notification object:(id)object handler:(id /* block */)handler;
- (id)expectationForNotification:(id)notification object:(id)object notificationCenter:(id)center handler:(id /* block */)handler;
- (id)expectationForPredicate:(id)predicate evaluatedWithObject:(id)object handler:(id /* block */)handler;
- (void)_waiter:(id)_waiter whileWaitingForWait:(id)wait didTimeoutWithUnfulfilledExpectations:(id)expectations;
- (void)_waiter:(id)_waiter whileWaitingForWait:(id)wait didFulfillInvertedExpectation:(id)expectation;
- (void)waiter:(id)waiter didTimeoutWithUnfulfilledExpectations:(id)expectations;
- (void)waiter:(id)waiter didFulfillInvertedExpectation:(id)expectation;
- (void)waiter:(id)waiter whileWaitingForWait:(id)wait didTimeoutWithUnfulfilledExpectations:(id)expectations;
- (void)waiter:(id)waiter whileWaitingForWait:(id)wait didFulfillInvertedExpectation:(id)expectation;
- (id)init;
- (id)_duplicate;
- (unsigned long long)testCaseCount;
- (id)_xctTestIdentifier;
- (id)languageAgnosticTestMethodName;
- (id)nameForLegacyLogging;
- (long long)defaultExecutionOrderCompare:(id)compare;
- (_Bool)isEqual:(id)equal;
- (void)dealloc;
- (void)recordSkipWithMessage:(id)message;
- (Class)_requiredTestRunBaseClass;
- (Class)testRunClass;
- (id)invokeTestMethod:(id *)method;
- (void)conditionallyRelaunchTestRunnerProcess;
- (void)performTest:(id)test;
- (_Bool)_testMethodSkippedWithXCTSkip;
- (_Bool)_shouldRepeatTest;
- (void)_purgeTeardownBlocks;
- (void)setUpTestWithSelector:(SEL)selector;
- (void)tearDownTestWithSelector:(SEL)selector;
- (void)_logMemoryGraphData:(id)data withTitle:(id)title;
- (void)_logMemoryGraphDataFromFilePath:(id)path withTitle:(id)title;
- (void)_skipWithoutRunningWithContext:(id)context;
- (void)_addExpectation:(id)expectation;
- (void)assertInvalidObjectsDeallocatedAfterScope:(id /* block */)scope;
- (void)assertObjectsOfTypes:(id)types invalidAfterScope:(id /* block */)scope;
- (void)assertObjectsOfType:(id)type invalidAfterScope:(id /* block */)scope;
- (void)markInvalid:(id)invalid;
- (void)assertNoLeaksInScope:(id /* block */)scope;
- (void)assertNoLeaksExcludingSystemTypesInScope:(id /* block */)scope;
- (void)memoryChecker:(id)checker didFailWithMessages:(id)messages serializedMemoryGraph:(id)graph;
- (void)_exceededExecutionTimeAllowance;
- (void)_startTimeoutTimer;
- (void)_stopTimeoutTimer;
- (void)_resetTimer;
- (id)_activityAggregateStatistics;
- (void)_setActivityAggregateStatistics:(id)statistics;
- (id)_testRunConfiguration;

@end

#endif /* XCTestCase_h */
