//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTElementSnapshotProvider_Protocol_h
#define XCTElementSnapshotProvider_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTElementSnapshotProvider <NSObject>

@required

/* required instance methods */
- (id)snapshotForElement:(id)element attributes:(id)attributes parameters:(id)parameters timeoutControls:(id)controls error:(id *)error;

@optional

@end

#endif /* XCTElementSnapshotProvider_Protocol_h */
