//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTestExpectation_h
#define XCTestExpectation_h
#import <XCTest/XCTestExpectation.h>
@import Foundation;
@import UIKit;

#include "XCTestExpectationDelegate-Protocol.h"

@class NSArray, NSLock, NSMutableArray, NSObject, NSString;

@interface XCTestExpectation (FBXCTestPrivate)


@property unsigned long long numberOfFulfillments;
@property (weak) id <XCTestExpectationDelegate> delegate;
@property (readonly) _Bool hasBeenWaitedOn;
@property (readonly) _Bool fulfilled;
@property (readonly) unsigned long long creationToken;
@property (readonly) unsigned long long fulfillmentToken;
@property (readonly, copy) NSArray *creationCallStackReturnAddresses;
@property (readonly, copy) NSArray *fulfillCallStackReturnAddresses;
@property (copy) NSString *_expectationDescription;
@property _Bool hasInverseBehavior;
@property (nonatomic) unsigned long long fulfillmentCount;

/* class methods */
+ (id)compoundAndExpectationWithSubexpectations:(id)subexpectations;
+ (id)compoundOrExpectationWithSubexpectations:(id)subexpectations;
+ (id)expectationWithDescription:(id)description;

/* instance methods */
- (id)init;
- (void)dealloc;
- (id)description;
- (id)_generateExpectationDescription;
- (_Bool)isInverted;
- (void)setHasBeenWaitedOn:(_Bool)on wait:(id)wait;
- (void)cleanup:(_Bool)cleanup;
- (void)addCleanupHandler:(id /* block */)handler;
- (void)_setExpectationDescription:(id)description;

@end

#endif /* XCTestExpectation_h */
