//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTestConfiguration_h
#define XCTestConfiguration_h
@import Foundation;
@import UIKit;

@class NSArray, NSDictionary, NSNumber, NSObject, NSSet, NSString, NSURL, NSUUID, XCTCapabilities, XCTAggregateSuiteRunStatistics, XCTRepetitionPolicy, XCTRuntimeDiagnosticsPolicy, XCTScreenCapturePolicy, XCTTestIdentifierSet, XCTTestSelection;

@interface XCTestConfiguration : NSObject <NSSecureCoding, NSCopying>

@property (copy) id /* block */ randomNumberGenerator;
@property (readonly, copy) NSString *testBundleName;
@property (copy) NSString *testBundleRelativePath;
@property _Bool reportResultsToIDE;
@property _Bool testsDrivenByIDE;
@property _Bool inProcessParallelizationEnabled;
@property (copy) NSUUID *sessionIdentifier;
@property _Bool disablePerformanceMetrics;
@property _Bool treatMissingBaselinesAsFailures;
@property (copy, nonatomic) NSURL *baselineFileURL;
@property (copy) NSString *baselineFileRelativePath;
@property (copy) NSString *targetApplicationPath;
@property (copy) NSString *targetApplicationBundleID;
@property (copy) NSString *productModuleName;
@property _Bool reportActivities;
@property _Bool testsMustRunOnMainThread;
@property _Bool initializeForUITesting;
@property _Bool emitOSLogs;
@property (copy) XCTAggregateSuiteRunStatistics *aggregateStatisticsBeforeCrash;
@property (copy, nonatomic) NSString *basePathForTestBundleResolution;
@property (copy) NSString *automationFrameworkPath;
@property long long systemAttachmentLifetime;
@property long long userAttachmentLifetime;
@property (nonatomic) long long preferredScreenCaptureFormat;
@property (readonly) XCTScreenCapturePolicy *effectiveScreenCapturePolicy;
@property long long testExecutionOrdering;
@property long long leaksCheckingMode;
@property (retain) NSNumber *randomExecutionOrderingSeed;
@property (retain) XCTRepetitionPolicy *repetitionPolicy;
@property (retain) XCTRuntimeDiagnosticsPolicy *runtimeDiagnosticsPolicy;
@property (retain) XCTCapabilities *IDECapabilities;
@property (copy) NSDictionary *applicationBundleInfos;
@property _Bool initializeForMultiDevice;
@property _Bool shouldExtractMultiDeviceRequirements;
@property _Bool runAsMultiDeviceRemoteRunner;
@property (copy) NSString *multiDeviceRequirementsFilePath;
@property (copy) NSDictionary *multiDeviceRemoteRunnerPlatformMap;
@property (copy) NSDictionary *multiDevicePlatformVersionMap;
@property (copy) NSSet *bundleIDsForCrashReportEmphasis;
@property (copy) NSSet *symbolicationImageNames;
@property (copy) XCTTestSelection *testSelection;
@property (copy) NSSet *testInstructionsSet;
@property (copy, nonatomic) NSURL *testBundleURL;
@property (copy) XCTTestIdentifierSet *testsToSkip;
@property (copy) XCTTestIdentifierSet *testsToRun;
@property (copy) NSDictionary *testApplicationDependencies;
@property (copy) NSDictionary *testApplicationUserOverrides;
@property (copy) NSArray *targetApplicationArguments;
@property (copy) NSDictionary *targetApplicationEnvironment;
@property _Bool gatherLocalizableStringsData;
@property (readonly) long long testMode;
@property _Bool testTimeoutsEnabled;
@property (copy, nonatomic) NSNumber *defaultTestExecutionTimeAllowance;
@property (copy, nonatomic) NSNumber *maximumTestExecutionTimeAllowance;
@property (copy) NSNumber *traceCollectionEnabled;
@property (copy) NSNumber *enablePerformanceTestsDiagnostics;
@property (copy) NSDictionary *performanceTestConfiguration;

/* class methods */
+ (_Bool)supportsSecureCoding;
+ (void)setActiveTestConfiguration:(id)configuration;
+ (id)activeTestConfiguration;
+ (_Bool)_isAppleInternal;
+ (id)defaultBasePathForTestBundleResolutionForMainBundlePath:(id)path;
+ (id)defaultBasePathForTestBundleResolution;

/* instance methods */
- (id)init;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (void)clearXcodeReportingConfiguration;

@end

#endif /* XCTestConfiguration_h */
