//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTest_h
#define XCTest_h
#import <XCTest/XCAbstractTest.h>
@import Foundation;
@import UIKit;

#include "XCTIssueHandling-Protocol.h"
@class NSBundle, NSDictionary, NSObject, NSString, XCTExpectedFailureContextManager, XCTSkippedTestContext, XCTTestIdentifier, XCTestObservationCenter, XCTestRun;

@interface XCTest (FBXCTestPrivate)


@property (readonly) NSString *_classNameForReporting;
@property (readonly) NSString *_methodNameForReporting;
@property (readonly) XCTTestIdentifier *identifier;
@property (readonly) Class _requiredTestRunBaseClass;
@property (readonly) NSString *languageAgnosticTestClassName;
@property (readonly) NSString *languageAgnosticTestMethodName;
@property (readonly) NSString *nameForLegacyLogging;
@property (retain) XCTestObservationCenter *observationCenter;
@property (retain) XCTSkippedTestContext *skippedTestContext;
@property (readonly) NSDictionary *activityAggregateStatistics;
@property (readonly) NSBundle *bundle;

/* class methods */
+ (id)bundle;

/* instance methods */
- (id)_duplicate;
- (void)_xct_setObservationCenter:(id)center;
- (id)_xct_observationCenter;
- (_Bool)_shouldRepeatTest;
- (long long)defaultExecutionOrderCompare:(id)compare;
- (void)handleIssue:(id)issue;
- (void)handleIssue:(id)issue completionHandler:(id /* block */)handler;
- (id)expectedFailureContextManager;
- (void)_checkForExpectedFailureMatchingIssue:(id)issue;
- (void)expectFailureWithContext:(id)context;
- (void)expectFailureWithContext:(id)context inBlock:(id /* block */)block;
- (id)_activityAggregateStatistics;
- (void)_removeTestsWithIdentifierInSet:(id)set;
- (void)_removeTestsWithoutIdentifierInSet:(id)set;
- (void)_skipWithoutRunningWithContext:(id)context;

@end

#endif /* XCTest_h */
