//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTestObservationCenter_h
#define XCTestObservationCenter_h
#import <XCTest/XCTestObservationCenter.h>
@import Foundation;
@import UIKit;

@class NSBundle, NSMutableArray, NSObject;

@interface XCTestObservationCenter (FBXCTestPrivate)

@property (readonly) NSMutableArray *observers;
@property (readonly) NSMutableArray *privateObservers;
@property (readonly) NSMutableArray *internalObservers;
@property _Bool suspended;
@property (readonly, copy) id /* block */ exceptionHandler;
@property (retain) NSBundle *currentTestBundle;
@property _Bool testBundleWillStartCalled;

/* class methods */
+ (id)sharedTestObservationCenter;
+ (void)setSharedTestObservationCenter:(id)center;

/* instance methods */
- (id)initWithObservers:(id)observers exceptionHandler:(id /* block */)handler;
- (id)init;
- (id)description;
- (void)addSystemTestObserver:(id)observer;
- (void)_addTestObserver:(id)observer atStart:(_Bool)start;
- (id)testObserverOfClass:(Class)_class;
- (void)_observeTestExecutionForTestBundle:(id)bundle inBlock:(id /* block */)block;
- (void)_resumeObservation;
- (void)_suspendObservation;
- (void)_suspendObservationForBlock:(id /* block */)block;
- (void)_handleExceptionThrownBy:(id)by inMethod:(SEL)method exceptionPointer:(id)pointer;
- (void)_callTestBundleWillStartIfNeeded;
- (void)_callTestBundleDidFinishIfNeeded;
- (void)_testSuiteDidStart:(id)start;
- (void)_testSuiteDidStop:(id)stop;
- (void)_testSuiteWasSkipped:(id)skipped withDescription:(id)description sourceCodeContext:(id)context;
- (void)_testSuite:(id)suite didRecordIssue:(id)issue;
- (void)_testSuite:(id)suite didRecordExpectedFailure:(id)failure;
- (void)_testCaseDidStart:(id)start;
- (void)_testCaseWasSkipped:(id)skipped withDescription:(id)description sourceCodeContext:(id)context;
- (void)_testCasePlaceholderRun:(id)run isUnavailableWithReason:(id)reason;
- (void)_testCaseDidStop:(id)stop;
- (void)_testCase:(id)_case didRecordIssue:(id)issue;
- (void)_testCase:(id)_case didRecordExpectedFailure:(id)failure;
- (void)_context:(id)_context willStartActivity:(id)activity;
- (void)_context:(id)_context didFinishActivity:(id)activity;
- (void)_performBlockOnObservers:(id)observers respondingToSelector:(SEL)selector reverse:(_Bool)reverse block:(id /* block */)block;

@end

#endif /* XCTestObservationCenter_h */
