//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTElementSnapshotAttributeDataSource_Protocol_h
#define XCTElementSnapshotAttributeDataSource_Protocol_h
@import Foundation;
@import UIKit;

#include "XCTMacCatalystStatusProviding-Protocol.h"

@protocol XCTElementSnapshotAttributeDataSource <XCTMacCatalystStatusProviding>

@required

@property (readonly) _Bool allowsRemoteAccess;
@property (readonly) _Bool supportsHostedViewCoordinateTransformations;
@property (readonly) _Bool usePointTransformationsForFrameConversions;
@property (readonly) _Bool hasBannerNotificationIsStickyAttribute;
@property (readonly) _Bool providesValuesForPrivilegedAttributes;

/* required instance methods */
- (id)attributesForElement:(id)element attributes:(id)attributes error:(id *)error;
- (id)valuesForPrivilegedAttributes:(id)attributes forElement:(id)element error:(id *)error;
- (id)parameterizedAttribute:(id)attribute forElement:(id)element parameter:(id)parameter error:(id *)error;

@optional

@end

#endif /* XCTElementSnapshotAttributeDataSource_Protocol_h */
