//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTestRun_h
#define XCTestRun_h
#import <XCTest/XCTestRun.h>
@import Foundation;
@import UIKit;

@class NSDate, NSObject, XCTIssue, XCTest, XCTestObservationCenter;

@interface XCTestRun (FBXCTestPrivate)

@property double startTimeInterval;
@property double stopTimeInterval;
@property _Bool hasStarted;
@property _Bool hasStopped;
@property _Bool hasExpectedFailure;
@property (retain) XCTIssue *candidateIssue;
@property unsigned long long _runCount;
@property unsigned long long executionCountBeforeCrash;
@property unsigned long long skipCountBeforeCrash;
@property unsigned long long expectedFailureCountBeforeCrash;
@property unsigned long long failureCountBeforeCrash;
@property unsigned long long unexpectedExceptionCountBeforeCrash;
@property (readonly) XCTestObservationCenter *observationCenter;

/* class methods */

/* instance methods */
- (void)recordFailureWithDescription:(id)description inFile:(id)file atLine:(unsigned long long)line expected:(_Bool)expected;
- (id)description;
- (unsigned long long)expectedFailureCount;
- (void)recordSkipWithDescription:(id)description sourceCodeContext:(id)context;
- (void)recordExpectedFailure:(id)failure;
- (void)_recordIssue:(id)issue;
- (void)_handleIssue:(id)issue;

@end

#endif /* XCTestRun_h */
