//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTElementSetTransformer_Protocol_h
#define XCTElementSetTransformer_Protocol_h
@import Foundation;
@import UIKit;

#include "XCTCapabilitiesProviding-Protocol.h"

@class NSSet, NSString;

@protocol XCTElementSetTransformer <NSObject, NSCopying, XCTCapabilitiesProviding>

@required

@property (copy) NSString *transformationDescription;
@property (readonly) _Bool supportsAttributeKeyPathAnalysis;
@property _Bool stopsOnFirstMatch;
@property (readonly, copy) NSSet *elementTypes;

/* required instance methods */
- (id)transform:(id)transform relatedElements:(id *)elements;
- (id)iteratorForInput:(id)input;
- (_Bool)canBeRemotelyEvaluatedWithCapabilities:(id)capabilities;
- (id)requiredKeyPathsOrError:(id *)error;

@optional

@end

#endif /* XCTElementSetTransformer_Protocol_h */
