//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTExpectedFailureContextManager_h
#define XCTExpectedFailureContextManager_h
@import Foundation;
@import UIKit;

#include "XCTIssueHandling-Protocol.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSObject;

@interface XCTExpectedFailureContextManager : NSObject

@property (readonly) NSMutableArray *threadAgnosticContextStack;
@property (readonly) NSMutableDictionary *contextStacksByThreadId;
@property (readonly, weak) id <XCTIssueHandling> issueHandler;
@property (readonly) NSArray *immutableExpectedFailureContextStackForCurrentThread;

/* instance methods */
- (id)initWithIssueHandler:(id)handler;
- (void)invalidate;
- (void)_cleanUpContext:(id)context;
- (id)expectedFailureContextStackForThreadWithId:(unsigned long long)id;
- (id)expectedFailureContextStackForCurrentThread;
- (void)pushExpectedFailureContext:(id)context;
- (void)popExpectedFailureContext:(id)context;
- (void)checkForExpectedFailureMatchingIssue:(id)issue;

@end

#endif /* XCTExpectedFailureContextManager_h */
