//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTestDriver_h
#define XCTestDriver_h
@import Foundation;
@import UIKit;

#include "XCTRunnerIDESessionDelegate-Protocol.h"
@class NSBundle, NSObject, NSString, NSURL, NSUUID, XCTFuture, XCTPromise, XCTReportingSession, XCTRunnerIDESession, XCTestConfiguration;

@interface XCTestDriver : NSObject <XCTRunnerIDESessionDelegate> {
    /* instance variables */
    XCTFuture *_executionWorkerFuture;
    XCTPromise *_executionWorkerPromise;
    XCTReportingSession *_reportingSession;
}

@property (retain) XCTRunnerIDESession *ideSession;
@property (readonly, copy) NSURL *testBundleURLFromEnvironment;
@property (readonly, copy) NSUUID *sessionIdentifierFromEnvironment;
@property (readonly, copy) NSURL *testConfigurationURLFromEnvironment;
@property (readonly, copy) NSString *testConfigurationEncodedValueFromEnvironment;
@property (readonly, copy) id /* block */ daemonSessionProvider;
@property (retain) XCTestConfiguration *testConfiguration;
@property (retain) NSBundle *testBundle;
@property (retain) id testBundlePrincipalClassInstance;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initializeSharedTestDriverWithRunConfiguration:(id)configuration;
+ (id)sharedTestDriver;
+ (id)testBundleURLFromEnvironment;
+ (_Bool)shouldSkipInitialBundleLoadBeforeXCTestMain;
+ (_Bool)environmentSpecifiesTestConfiguration;
+ (void)_applyRandomExecutionOrderingSeed:(id)seed;

/* instance methods */
- (id)initWithTestConfiguration:(id)configuration;
- (int)run;
- (int)_prepareTestConfigurationAndIDESession;
- (void)_configureGlobalState;
- (_Bool)_preTestingInitialization;
- (id)suspendAppSleep;
- (int)_runTests;
- (void)flushIDEConnectionAndExitWithCode:(int)code timeout:(double)timeout;
- (void)_reportFinishedExecutingTests;
- (id)_prepareIDESessionWithIdentifier:(id)identifier exitCode:(int *)code;
- (void)_reportBootstrappingFailure:(id)failure;
- (id)_loadTestBundleFromURL:(id)url error:(id *)error;
- (void)_createTestBundlePrincipalClassInstance;
- (Class)_declaredPrincipalClassFromTestBundle:(id)bundle;
- (id)harnessEventReporter;
- (void)IDESessionDidDisconnect:(id)disconnect;
- (void)testWorkerForIDESession:(id)idesession completion:(id /* block */)completion;

@end

#endif /* XCTestDriver_h */
