//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTFuture_h
#define XCTFuture_h
@import Foundation;
@import UIKit;

@class NSError, NSMutableSet, NSObject, XCTPromise, XCTWaiter;

@interface XCTFuture : NSObject {
    /* instance variables */
    struct __CFRunLoop * _runLoopUsedWhenWaiting;
}

@property (readonly) double startTime;
@property (readonly) double deadline;
@property (readonly) XCTPromise *promise;
@property (readonly) XCTWaiter *waiter;
@property _Bool hasWaited;
@property _Bool hasFinished;
@property (readonly) NSMutableSet *cancelationExpectations;
@property (readonly) id value;
@property (readonly) NSError *error;
@property (readonly, getter=isCanceled) _Bool canceled;
@property (readonly) double executionTime;

/* class methods */
+ (id)futureWithTimeout:(double)timeout description:(id)description block:(id /* block */)block;
+ (id)futureWithDescription:(id)description block:(id /* block */)block;

/* instance methods */
- (id)initWithTimeout:(double)timeout promise:(id)promise;
- (void)_waitForFulfillment;
- (void)_waitForFulfillmentWithCompletion:(id /* block */)completion;
- (void)_waitForFulfillmentSync:(_Bool)sync withCompletion:(id /* block */)completion;
- (void)addCancelationExpectation:(id)expectation;
- (void)valueWithCompletion:(id /* block */)completion;

@end

#endif /* XCTFuture_h */
