//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTHarnessEventReporting_Protocol_h
#define XCTHarnessEventReporting_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTHarnessEventReporting <NSObject>

@required

/* required instance methods */
- (void)reportBootstrappingFailure:(id)failure completion:(id /* block */)completion;
- (void)reportDidBeginExecutingTestPlan;
- (void)reportDidFinishExecutingTestPlanWithCompletion:(id /* block */)completion;
- (void)reportInitializationForUITestingFinishedWithError:(id)error;
- (void)reportStallOnMainThreadInTestCase:(id)_case file:(id)file line:(unsigned long long)line;
- (void)reportSelfDiagnosisIssue:(id)issue description:(id)description;
- (void)reportTestWithIdentifier:(id)identifier didExceedExecutionTimeAllowance:(double)allowance;

@optional

@end

#endif /* XCTHarnessEventReporting_Protocol_h */
