//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTIssue_h
#define XCTIssue_h
#import <XCTest/XCTIssue.h>
@import Foundation;
@import UIKit;

@class NSArray, NSData, NSDate, NSError, NSObject, NSString, NSUUID, XCTSourceCodeContext;

@interface XCTIssue (FBXCTestPrivate)

@property (copy) NSDate *timestamp;
@property struct {  _Bool x0;  } failureBreakPointCalled;
@property (copy) NSData *expectationSnapshotData;
@property (retain) NSUUID *UUID;
@property (readonly) _Bool isLegacyExpectedFailure;
@property unsigned long long threadId;
@property (copy) NSString *expectedFailureReason;
@property _Bool isExpectedFailure;
@property _Bool didInterruptTest;
@property _Bool shouldInterruptTest;

/* class methods */
+ (id)performanceDiagnosticsDelegateIdentifierPrefix;
+ (id)issueWithType:(long long)type compactDescription:(id)description associatedError:(id)error;
+ (id)issueWithException:(id)exception;
+ (id)issueWithExceptionPointer:(id)pointer;
+ (id)issueWithType:(long long)type compactDescription:(id)description callStackAddresses:(id)addresses filePath:(id)path lineNumber:(long long)number;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (void)_updateAttachmentsTimestamps;
- (id)description;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (_Bool)matchesLegacyPropertiesOfIssue:(id)issue;

@end

#endif /* XCTIssue_h */
