//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingRole_UIAutomation_Protocol_h
#define XCTMessagingRole_UIAutomation_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTMessagingRole_UIAutomation

@required

/* required instance methods */
- (id)_XCT_didBeginInitializingForUITesting;
- (id)_XCT_initializationForUITestingDidFailWithError:(id)error;
- (id)_XCT_requestDiagnosticsForAdditionalDevices:(id)devices;
- (id)_XCT_launchProcessWithPath:(id)path bundleID:(id)id arguments:(id)arguments environmentVariables:(id)variables;
- (id)_XCT_openURL:(id)url processPath:(id)path bundleID:(id)id arguments:(id)arguments environmentVariables:(id)variables;
- (id)_XCT_terminateProcess:(id)process;
- (id)_XCT_getProgressForLaunch:(id)launch;

@optional

@end

#endif /* XCTMessagingRole_UIAutomation_Protocol_h */
