//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingRole_SiriAutomation_Protocol_h
#define XCTMessagingRole_SiriAutomation_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTMessagingRole_SiriAutomation

@required

/* required instance methods */
- (void)_XCT_requestSiriEnabledStatus:(id /* block */)status;
- (void)_XCT_startSiriUIRequestWithText:(id)text completion:(id /* block */)completion;
- (void)_XCT_startSiriUIRequestWithAudioFileURL:(id)url completion:(id /* block */)completion;
- (void)_XCT_injectAssistantRecognitionStrings:(id)strings completion:(id /* block */)completion;
- (void)_XCT_injectVoiceRecognitionAudioInputPaths:(id)paths completion:(id /* block */)completion;

@optional

@end

#endif /* XCTMessagingRole_SiriAutomation_Protocol_h */
