//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingRole_SignpostRequesting_Protocol_h
#define XCTMessagingRole_SignpostRequesting_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTMessagingRole_SignpostRequesting

@required

/* required instance methods */
- (void)_XCT_registerForSignpostsFromSubsystem:(id)subsystem category:(id)category intervalTimeout:(double)timeout reply:(id /* block */)reply;
- (void)_XCT_unregisterForSignpostsWithToken:(id)token;

@optional

@end

#endif /* XCTMessagingRole_SignpostRequesting_Protocol_h */
