//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingRole_ProcessMonitoring_Protocol_h
#define XCTMessagingRole_ProcessMonitoring_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTMessagingRole_ProcessMonitoring

@required

/* required instance methods */
- (id)_IDE_processWithBundleID:(id)id path:(id)path pid:(id)pid crashedUnderSymbol:(id)symbol;
- (id)_IDE_stopTrackingProcessWithToken:(id)token;
- (id)_IDE_processWithToken:(id)token exitedWithStatus:(id)status;

@optional

@end

#endif /* XCTMessagingRole_ProcessMonitoring_Protocol_h */
