//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingRole_SystemConfiguration_Protocol_h
#define XCTMessagingRole_SystemConfiguration_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTMessagingRole_SystemConfiguration

@required

/* required instance methods */
- (void)_XCT_updateAppearanceMode:(long long)mode completion:(id /* block */)completion;
- (void)_XCT_getAppearanceModeWithReply:(id /* block */)reply;
- (void)_XCT_getSimulatedLocationWithReply:(id /* block */)reply;
- (void)_XCT_setSimulatedLocation:(id)location reply:(id /* block */)reply;
- (void)_XCT_clearSimulatedLocationWithReply:(id /* block */)reply;

@optional

@end

#endif /* XCTMessagingRole_SystemConfiguration_Protocol_h */
