//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingRole_CapabilityExchange_Protocol_h
#define XCTMessagingRole_CapabilityExchange_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTMessagingRole_CapabilityExchange

@required

/* required instance methods */
- (void)_XCT_exchangeCapabilities:(id)capabilities reply:(id /* block */)reply;
- (void)_XCT_requestSerializedTransportWrapperForIDESessionWithIdentifier:(id)identifier reply:(id /* block */)reply;
- (void)_XCT_requestBackgroundAssertionForPID:(int)pid reply:(id /* block */)reply;
- (void)_XCT_enableAutomationModeWithReply:(id /* block */)reply;
- (void)_XCT_requestEndpointForTestTargetWithPID:(int)pid preferredBackendPath:(id)path reply:(id /* block */)reply;
- (void)_XCT_requestUnsupportedBundleIdentifiersForAutomationSessions:(id /* block */)sessions;
- (void)_XCT_requestSpindumpWithSpecification:(id)specification completion:(id /* block */)completion;
- (void)_XCT_requestTailspinWithRequest:(id)request completion:(id /* block */)completion;
- (void)_XCT_requestScreenshot:(id)screenshot withReply:(id /* block */)reply;
- (void)_XCT_requestScreenshotAttachment:(id)attachment withReply:(id /* block */)reply;
- (void)_XCT_requestScreenshotOfScreenWithID:(unsigned int)id withRect:(CGRect)rect uti:(id)uti compressionQuality:(double)quality withReply:(id /* block */)reply;
- (void)_XCT_requestScreenshotWithReply:(id /* block */)reply;
- (void)_XCT_fetchAttributes:(id)attributes forElement:(id)element reply:(id /* block */)reply;
- (void)_XCT_requestElementAtPoint:(CGPoint)point reply:(id /* block */)reply;
- (void)_XCT_fetchSnapshotForElement:(id)element attributes:(id)attributes parameters:(id)parameters reply:(id /* block */)reply;
- (void)_XCT_runAccessibilityAuditForElement:(id)element withConfiguration:(id)configuration reply:(id /* block */)reply;
- (void)_XCT_startMonitoringApplicationWithBundleID:(id)id;
- (void)_XCT_startMonitoringApplicationWithBundleID:(id)id path:(id)path;
- (void)_XCT_launchApplicationWithBundleID:(id)id arguments:(id)arguments environment:(id)environment completion:(id /* block */)completion;
- (void)_XCT_launchApplicationWithBundleID:(id)id path:(id)path arguments:(id)arguments environment:(id)environment completion:(id /* block */)completion;
- (void)_XCT_terminateApplicationWithBundleID:(id)id completion:(id /* block */)completion;
- (void)_XCT_terminateApplicationWithBundleID:(id)id pid:(int)pid completion:(id /* block */)completion;
- (void)_XCT_openDefaultApplicationForURL:(id)url completion:(id /* block */)completion;
- (void)_XCT_openURL:(id)url usingApplication:(id)application completion:(id /* block */)completion;
- (void)_XCT_registerForAccessibilityNotification:(int)notification reply:(id /* block */)reply;
- (void)_XCT_unregisterForAccessibilityNotification:(int)notification withRegistrationToken:(id)token reply:(id /* block */)reply;
- (void)_XCT_performAccessibilityAction:(int)action onElement:(id)element withValue:(id)value reply:(id /* block */)reply;
- (void)_XCT_snapshotForElement:(id)element attributes:(id)attributes parameters:(id)parameters reply:(id /* block */)reply;
- (void)_XCT_requestSnapshotForElement:(id)element attributes:(id)attributes parameters:(id)parameters reply:(id /* block */)reply;
- (void)_XCT_fetchAttributesForElement:(id)element attributes:(id)attributes reply:(id /* block */)reply;
- (void)_XCT_setAttribute:(id)attribute value:(id)value element:(id)element reply:(id /* block */)reply;
- (void)_XCT_fetchParameterizedAttributeForElement:(id)element attributes:(id)attributes parameter:(id)parameter reply:(id /* block */)reply;
- (void)_XCT_fetchParameterizedAttribute:(id)attribute forElement:(id)element parameter:(id)parameter reply:(id /* block */)reply;
- (void)_XCT_checkForContinuityWithReply:(id /* block */)reply;

@optional

@end

#endif /* XCTMessagingRole_CapabilityExchange_Protocol_h */
