//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMetricDiagnosticHelper_h
#define XCTMetricDiagnosticHelper_h
@import Foundation;
@import UIKit;

@class NSArray, NSObject, XCTAttachmentManager, XCTMeasureOptions, XCTMemoryChecker, XCTTestIdentifier;

@interface XCTMetricDiagnosticHelper : NSObject {
    /* instance variables */
    XCTAttachmentManager *_attachmentManager;
}

@property (copy, nonatomic) NSArray *metrics;
@property (copy, nonatomic) NSArray *memoryMetrics;
@property (retain) XCTTestIdentifier *testIdentifier;
@property (copy, nonatomic) XCTMeasureOptions *measureOptions;
@property (retain, nonatomic) XCTMemoryChecker *memoryChecker;

/* class methods */
+ (id)generateRandomString;

/* instance methods */
- (id)initWithMetrics:(id)metrics attachmentManager:(id)manager options:(id)options testIdentifier:(id)identifier;
- (id)_sanitizeFileNameString:(id)string;
- (id)_generateTraceName;
- (void)_applyDefaultTraceName;
- (void)_applyXcodebuildCommandLineOverridesToOptions:(id)options;
- (void)sendMetricUseToCoreAnalytics:(id)analytics;
- (void)attachTraceFileCollectedForInstrument:(id)instrument;
- (void)attachPerfdataFileCollected:(id)collected;
- (void)performMemoryDiagnosticRunForBlock:(id /* block */)block;
- (void)collectMemgraphsForPregeneration:(_Bool)pregeneration;
- (void)attachMemgraphsForMetric:(id)metric;
- (id)getMemgraphDataForPid:(int)pid error:(id *)error;
- (id)getPidForProcessName:(id)name error:(id *)error;
- (int)setMallocStackLoggingForPregeneration:(_Bool)pregeneration forPid:(id)pid error:(id *)error;
- (id)generateCompressedMemgraphDirectory:(id)directory;
- (void)setMallocStackLoggingForRunnerProcessForPregeneration:(_Bool)pregeneration;
- (void)addAttachment:(id)attachment;

@end

#endif /* XCTMetricDiagnosticHelper_h */
