//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingRole_TestReporting_Protocol_h
#define XCTMessagingRole_TestReporting_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTMessagingRole_TestReporting

@required

/* required instance methods */
- (id)_XCT_didFailToBootstrapWithError:(id)error;
- (id)_XCT_reportTestWithIdentifier:(id)identifier didExceedExecutionTimeAllowance:(id)allowance;
- (id)_XCT_testRunnerReadyWithCapabilities:(id)capabilities;
- (id)_XCT_didBeginExecutingTestPlan;
- (id)_XCT_didFinishExecutingTestPlan;
- (id)_XCT_didFormPlanWithData:(id)data;
- (id)_XCT_testSuiteWithIdentifier:(id)identifier didStartAt:(id)at traits:(id)traits;
- (id)_XCT_testSuiteWithIdentifier:(id)identifier didStartAt:(id)at;
- (id)_XCT_testSuiteWithIdentifier:(id)identifier didRecordIssue:(id)issue;
- (id)_XCT_testSuiteWithIdentifier:(id)identifier wasSkippedWithMessage:(id)message sourceCodeContext:(id)context;
- (id)_XCT_testCaseDidStartWithIdentifier:(id)identifier testCaseRunConfiguration:(id)configuration traits:(id)traits;
- (id)_XCT_testCaseDidStartWithIdentifier:(id)identifier testCaseRunConfiguration:(id)configuration;
- (id)_XCT_testCaseWithIdentifier:(id)identifier wasSkippedWithMessage:(id)message sourceCodeContext:(id)context;
- (id)_XCT_testCaseWithIdentifier:(id)identifier didRecordIssue:(id)issue;
- (id)_XCT_testCaseWithIdentifier:(id)identifier didRecordExpectedFailure:(id)failure;
- (id)_XCT_testCaseWithIdentifier:(id)identifier didFinishWithStatus:(id)status duration:(id)duration;
- (id)_XCT_testCaseWithIdentifier:(id)identifier didStallOnMainThreadInFile:(id)file line:(id)line;
- (id)_XCT_testWithIdentifier:(id)identifier didRecordIssue:(id)issue;

@optional

@end

#endif /* XCTMessagingRole_TestReporting_Protocol_h */
