//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingChannel_RunnerToDaemon_Protocol_h
#define XCTMessagingChannel_RunnerToDaemon_Protocol_h
@import Foundation;
@import UIKit;

#include "XCTMessagingRole_BundleRequesting-Protocol.h"
#include "XCTMessagingRole_CapabilityExchange-Protocol.h"
#include "XCTMessagingRole_EventSynthesis-Protocol.h"
#include "XCTMessagingRole_ForcePressureSupportQuerying-Protocol.h"
#include "XCTMessagingRole_HIDEventRecording-Protocol.h"
#include "XCTMessagingRole_MemoryTesting-Protocol.h"
#include "XCTMessagingRole_ProtectedResourceAuthorization-Protocol.h"
#include "XCTMessagingRole_ScreenRecording-Protocol.h"
#include "XCTMessagingRole_SignpostRequesting-Protocol.h"
#include "XCTMessagingRole_SiriAutomation-Protocol.h"
#include "XCTMessagingRole_SystemConfiguration-Protocol.h"
#include "XCTMessagingRole_TelemetrySending-Protocol.h"
#include "XCTMessagingRole_UIAutomationRunnerEventReporting-Protocol.h"
#include "XCTMessagingRole_UserPresence-Protocol.h"
#include "_XCTMessaging_VoidProtocol-Protocol.h"

@protocol XCTMessagingChannel_RunnerToDaemon <XCTMessagingRole_BundleRequesting, XCTMessagingRole_CapabilityExchange, XCTMessagingRole_MemoryTesting, XCTMessagingRole_ProtectedResourceAuthorization, XCTMessagingRole_TelemetrySending, XCTMessagingRole_EventSynthesis, XCTMessagingRole_ForcePressureSupportQuerying, XCTMessagingRole_HIDEventRecording, XCTMessagingRole_ScreenRecording, XCTMessagingRole_SignpostRequesting, XCTMessagingRole_SiriAutomation, XCTMessagingRole_SystemConfiguration, XCTMessagingRole_UserPresence, XCTMessagingRole_UIAutomationRunnerEventReporting, _XCTMessaging_VoidProtocol>

@required

@optional

/* optional instance methods */
- (void)__dummy_method_to_work_around_68987191;

@end

#endif /* XCTMessagingChannel_RunnerToDaemon_Protocol_h */
