//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingRole_ActivityReporting_Protocol_h
#define XCTMessagingRole_ActivityReporting_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTMessagingRole_ActivityReporting

@required

/* required instance methods */
- (id)_XCT_testCaseWithIdentifier:(id)identifier willStartActivity:(id)activity;
- (id)_XCT_testCaseWithIdentifier:(id)identifier didFinishActivity:(id)activity;

@optional

@end

#endif /* XCTMessagingRole_ActivityReporting_Protocol_h */
