//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMemoryChecker_h
#define XCTMemoryChecker_h
@import Foundation;
@import UIKit;

#include "XCTMemoryCheckerDelegate-Protocol.h"

@class DTXConnection, NSMutableSet, NSObject;

@interface XCTMemoryChecker : NSObject

@property (retain) NSMutableSet *markedAddresses;
@property (retain, nonatomic) DTXConnection *dtxConnection;
@property (readonly, getter=isConnectedToService) _Bool connectedToService;
@property (weak) id <XCTMemoryCheckerDelegate> delegate;

/* instance methods */
- (id)init;
- (id)initWithDelegate:(id)delegate;
- (id)_getGraphDataOfType:(long long)type forPID:(int)pid withError:(id *)error;
- (int)_setMallocStackLoggingMode:(int)mode forPid:(int)pid withError:(id *)error;
- (id)_getRunningProcesses:(id *)processes;
- (void)_assertInvalidObjectsDeallocatedAfterScope:(id /* block */)scope;
- (void)_markInvalid:(id)invalid;
- (void)_assertObjectsOfTypes:(id)types inProcess:(int)process invalidAfterScope:(id /* block */)scope;
- (void)_assertNoLeaksInProcessWithIdentifier:(int)identifier withOptions:(long long)options inScope:(id /* block */)scope;
- (id)_acquireMemoryGenerationForPID:(int)pid withError:(id *)error;
- (void)_assertNoObjectAbandonedBetweenGeneration:(id)generation and:(id)_and;
- (void)assertInvalidObjectsDeallocatedAfterScope:(id /* block */)scope;
- (void)assertObjectsOfTypes:(id)types invalidAfterScope:(id /* block */)scope;
- (void)assertObjectsOfType:(id)type invalidAfterScope:(id /* block */)scope;
- (void)assertNoLeaksExcludingSystemTypesInScope:(id /* block */)scope;
- (void)markInvalid:(id)invalid;
- (void)assertNoLeaksInScope:(id /* block */)scope;
- (void)assertNoLeaksWithOptions:(long long)options inScope:(id /* block */)scope;
- (void)assertNoLeaksInProcessWithIdentifier:(int)identifier withOptions:(long long)options inScope:(id /* block */)scope;
- (id)acquireGenerationMemoryGraphWithError:(id *)error;
- (id)acquireGenerationMemoryGraphForPid:(int)pid withError:(id *)error;
- (id)aquireGenerationMemoryGraphForPid:(int)pid withError:(id *)error;
- (void)assertNoObjectAbandonmentBetweenGeneration:(id)generation and:(id)_and;

@end

#endif /* XCTMemoryChecker_h */
