//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingRole_EventSynthesis_Protocol_h
#define XCTMessagingRole_EventSynthesis_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTMessagingRole_EventSynthesis

@required

/* required instance methods */
- (void)_XCT_setAXTimeout:(double)axtimeout reply:(id /* block */)reply;
- (void)_XCT_loadAccessibilityWithTimeout:(double)timeout reply:(id /* block */)reply;
- (void)_XCT_synthesizeEvent:(id)event completion:(id /* block */)completion;
- (void)_XCT_performDeviceEvent:(id)event completion:(id /* block */)completion;
- (void)_XCT_updateDeviceOrientation:(long long)orientation completion:(id /* block */)completion;
- (void)_XCT_getDeviceOrientationWithCompletion:(id /* block */)completion;
- (void)_XCT_sendString:(id)string maximumFrequency:(unsigned long long)frequency completion:(id /* block */)completion;
- (void)_XCT_unloadAccessibility:(id /* block */)accessibility;
- (void)_XCT_setLocalizableStringsDataGatheringEnabled:(_Bool)enabled reply:(id /* block */)reply;
- (void)_XCT_enableFauxCollectionViewCells:(id /* block */)cells;
- (void)_XCT_getInterfaceOrientationWithCompletion:(id /* block */)completion;
- (void)_XCT_hasHardwareButton:(id)button completion:(id /* block */)completion;

@optional

@end

#endif /* XCTMessagingRole_EventSynthesis_Protocol_h */
