//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingChannel_IDEToRunner_Protocol_h
#define XCTMessagingChannel_IDEToRunner_Protocol_h
@import Foundation;
@import UIKit;

#include "XCTMessagingRole_ProcessMonitoring-Protocol.h"
#include "XCTMessagingRole_TestExecution-Protocol.h"
#include "_XCTMessaging_VoidProtocol-Protocol.h"

@protocol XCTMessagingChannel_IDEToRunner <XCTMessagingRole_TestExecution, XCTMessagingRole_ProcessMonitoring, _XCTMessaging_VoidProtocol>

@required

@optional

/* optional instance methods */
- (void)__dummy_method_to_work_around_68987191;

@end

#endif /* XCTMessagingChannel_IDEToRunner_Protocol_h */
