//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingRole_ForcePressureSupportQuerying_Protocol_h
#define XCTMessagingRole_ForcePressureSupportQuerying_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTMessagingRole_ForcePressureSupportQuerying

@required

/* required instance methods */
- (void)_XCT_requestPressureEventsSupported:(id /* block */)supported;
- (void)_XCT_synthesizeEvent:(id)event implicitConfirmationInterval:(double)interval completion:(id /* block */)completion;
- (void)_XCT_requestCurrentKeyboardModifierFlagsWithReply:(id /* block */)reply;

@optional

@end

#endif /* XCTMessagingRole_ForcePressureSupportQuerying_Protocol_h */
