//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingChannel_RunnerToIDE_Protocol_h
#define XCTMessagingChannel_RunnerToIDE_Protocol_h
@import Foundation;
@import UIKit;

#include "XCTMessagingRole_ActivityReporting-Protocol.h"
#include "XCTMessagingRole_AttachmentFutureResultStatusUpdating-Protocol.h"
#include "XCTMessagingRole_DebugLogging-Protocol.h"
#include "XCTMessagingRole_PerformanceMeasurementReporting-Protocol.h"
#include "XCTMessagingRole_SelfDiagnosisIssueReporting-Protocol.h"
#include "XCTMessagingRole_TestReporting-Protocol.h"
#include "XCTMessagingRole_UIAutomation-Protocol.h"
#include "_XCTMessaging_VoidProtocol-Protocol.h"

@protocol XCTMessagingChannel_RunnerToIDE <XCTMessagingRole_DebugLogging, XCTMessagingRole_TestReporting, XCTMessagingRole_SelfDiagnosisIssueReporting, XCTMessagingRole_UIAutomation, XCTMessagingRole_ActivityReporting, XCTMessagingRole_PerformanceMeasurementReporting, XCTMessagingRole_AttachmentFutureResultStatusUpdating, _XCTMessaging_VoidProtocol>

@required

@optional

/* optional instance methods */
- (void)__dummy_method_to_work_around_68987191;

@end

#endif /* XCTMessagingChannel_RunnerToIDE_Protocol_h */
