//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMemoryCheckerDelegate_Protocol_h
#define XCTMemoryCheckerDelegate_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTMemoryCheckerDelegate <NSObject>

@required

/* required instance methods */
- (void)memoryChecker:(id)checker didFailWithMessages:(id)messages serializedMemoryGraph:(id)graph;

@optional

/* optional instance methods */
- (void)memoryChecker:(id)checker didFailForProcess:(id)process withRootLeakCounts:(id)counts leaksOutput:(id)output serializedLeakDiffMemoryGraph:(id)graph;

@end

#endif /* XCTMemoryCheckerDelegate_Protocol_h */
