//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingRole_TestExecution_Protocol_h
#define XCTMessagingRole_TestExecution_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTMessagingRole_TestExecution

@required

/* required instance methods */
- (id)_IDE_startExecutingTestPlanWithProtocolVersion:(id)version;
- (id)_IDE_fetchParallelizableTestIdentifiers;
- (id)_IDE_fetchAllTestIdentifiers;
- (id)_IDE_enumerateTests:(id)tests;
- (id)_IDE_executeTestsWithIdentifiersToRun:(id)run identifiersToSkip:(id)skip;
- (id)_IDE_shutdown;

@optional

@end

#endif /* XCTMessagingRole_TestExecution_Protocol_h */
