//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMeasureOptions_h
#define XCTMeasureOptions_h
#import <XCTest/XCTMeasureOptions.h>
@import Foundation;
@import UIKit;

@class NSArray, NSDictionary, NSObject, NSString;

@interface XCTMeasureOptions (FBXCTestPrivate)


@property (readonly, nonatomic) unsigned long long instrumentAutomatic;
@property (nonatomic) _Bool allowContinuousSampling;
@property (nonatomic) _Bool allowConcurrentIterations;
@property (retain, nonatomic) NSDictionary *performanceTestConfiguration;
@property (copy, nonatomic) NSArray *performanceTraceConfigurations;
@property (nonatomic) _Bool functionCoverageEnabled;
@property (copy, nonatomic) NSDictionary *functionCoverageConfiguration;
@property (retain, nonatomic) NSString *perfdataTestName;
@property (nonatomic) _Bool skipMetricMeasurement;
@property (retain, nonatomic) NSArray *uncacheBetweenIterations;
@property (retain, nonatomic) NSArray *terminateProcessBetweenIterations;
@property (nonatomic) _Bool shouldReportFailures;
@property (nonatomic) _Bool discardFirstIteration;
@property (nonatomic) _Bool traceCollectionEnabled;
@property (nonatomic) _Bool memgraphCollectionEnabled;
@property (nonatomic) _Bool perfdataAttachmentEnabled;
@property (nonatomic) double quiesceCpuIdlePercent;
@property (nonatomic) double quiesceCpuIdleTimeLimit;
@property (readonly, nonatomic) NSDictionary *instrumentOptions;

/* class methods */
+ (id)defaultOptions;

/* instance methods */
- (id)init;
- (id)initWithInstrumentOptionsDictionary:(id)dictionary;
- (void)applyPerformanceTestConfiguration;

@end

#endif /* XCTMeasureOptions_h */
