//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTMessagingRole_UIAutomationRunnerEventReporting_Protocol_h
#define XCTMessagingRole_UIAutomationRunnerEventReporting_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTMessagingRole_UIAutomationRunnerEventReporting

@required

/* required instance methods */
- (void)_XCT_recordedFirstResponderChangedWithApplicationSnapshot:(id)snapshot;
- (void)_XCT_recordedKeyEventsWithApplicationSnapshot:(id)snapshot characters:(id)characters charactersIgnoringModifiers:(id)modifiers modifierFlags:(id)flags;
- (void)_XCT_recordedOrientationChange:(id)change;
- (void)_XCT_recordedApplicationActivated:(id)activated;
- (void)_XCT_recordedEventNames:(id)names timestamp:(id)timestamp duration:(id)duration applicationSnapshot:(id)snapshot accessibilityElement:(id)element modifierFlags:(id)flags;

@optional

@end

#endif /* XCTMessagingRole_UIAutomationRunnerEventReporting_Protocol_h */
