//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTPromise_h
#define XCTPromise_h
@import Foundation;
@import UIKit;

@class NSError, NSObject, NSString, XCTestExpectation;

@interface XCTPromise : NSObject

@property (readonly) XCTestExpectation *expectation;
@property (retain) id value;
@property (retain) NSError *error;
@property (readonly) struct {  _Atomic _Bool x0;  } promiseFulfilled;
@property (readonly, copy) NSString *promiseDescription;

/* instance methods */
- (id)initWithDescription:(id)description;
- (void)fulfillWithValue:(id)value;
- (void)fulfillWithError:(id)error;
- (void)fulfillWithValue:(id)value error:(id)error;

@end

#endif /* XCTPromise_h */
