//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTReportingSessionTestReporter_h
#define XCTReportingSessionTestReporter_h
@import Foundation;
@import UIKit;

#include "XCTReportingSessionIssueReporter-Protocol.h"
@class NSObject, XCTTestIdentifier;

@interface XCTReportingSessionTestReporter : NSObject <XCTReportingSessionIssueReporter> {
    /* instance variables */
     id context;
     id parentId;
     id uuid;
}

@property (nonatomic, readonly) XCTTestIdentifier *identifier;
@property (nonatomic, readonly) id /* block */ finishHandler;
@property (nonatomic) double startReference;
@property (nonatomic) _Bool recordedExpectedFailure;
@property (nonatomic) _Bool recordedSkip;
@property (nonatomic) _Bool recordedFailure;

/* class methods */
+ (id)statusForTestThatFailed:(_Bool)failed orWasSkipped:(_Bool)skipped orFailedExpectedly:(_Bool)expectedly;

/* instance methods */
- (id)initWithIdentifier:(id)identifier context:(id)context parentId:(id)id finishHandler:(id /* block */)handler;
- (void)reportStartedWith:(id)with at:(id)at traits:(id)traits;
- (void)reportIssue:(id)issue atDate:(id)date;
- (void)reportAttachment:(id)attachment atDate:(id)date;
- (void)reportSkipWithDescription:(id)description sourceCodeContext:(id)context;
- (void)reportExecutionTimeAllowanceExceeded:(double)exceeded;
- (void)reportMeasuredMetric:(id)metric sourceCodeContext:(id)context;
- (void)reportExpectedFailure:(id)failure;
- (void)finishWithStatus:(id)status atDate:(id)date;
- (void)finishAtDate:(id)date;
- (void)reportActivityStarted:(id)started;
- (id)reportActivityStartedWithName:(id)name atDate:(id)date;
- (id)startActivity:(id)activity;
- (void)reportActivityFinished:(id)finished;
- (id)init;

@end

#endif /* XCTReportingSessionTestReporter_h */
