//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTRunnerIDESession_h
#define XCTRunnerIDESession_h
@import Foundation;
@import UIKit;

#include "XCDebugLogDelegate-Protocol.h"
#include "XCTHarnessEventReporting-Protocol.h"
#include "XCTMessagingChannel_IDEToRunner-Protocol.h"
#include "XCTMessagingChannel_RunnerToIDE-Protocol.h"
#include "XCTMessagingRole_ProcessMonitoring-Protocol.h"
#include "XCTMessagingRole_TestExecution-Protocol.h"
#include "XCTRunnerIDESessionDelegate-Protocol.h"
#include "_XCTestObservationInternal-Protocol.h"

@class DTXConnection, NSMutableArray, NSObject, NSString, XCTCapabilities, XCTFuture, XCTPromise, XCTReportingSession, XCTReportingSessionTestReporter, XCTestRun;
@protocol XCUIApplicationMonitor;

@interface XCTRunnerIDESession : NSObject <XCTMessagingChannel_IDEToRunner, _XCTestObservationInternal, XCTMessagingRole_ProcessMonitoring, XCTMessagingRole_TestExecution, XCTHarnessEventReporting, XCDebugLogDelegate> {
    /* instance variables */
    struct {  unsigned int _os_unfair_lock_opaque;  } _lock;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) DTXConnection *IDEConnection;
@property (readonly) id <XCTMessagingChannel_RunnerToIDE, NSObject> IDEProxy;
@property (readonly) XCTPromise *readyForTestingPromise;
@property (readonly) XCTPromise *IDEProxyPromise;
@property (retain) XCTReportingSessionTestReporter *currentTestReporter;
@property (retain) XCTCapabilities *IDECapabilities;
@property (copy) id /* block */ readinessReply;
@property (retain) XCTestRun *currentTestRun;
@property (retain) NSMutableArray *suiteReporters;
@property long long runningTestSuiteCount;
@property (readonly) XCTFuture *testConfigurationFuture;
@property (readonly) XCTFuture *readyForTestingFuture;
@property (readonly) XCTFuture *IDEProxyFuture;
@property (retain) XCTReportingSession *reportingSession;
@property (weak) id <XCTRunnerIDESessionDelegate> delegate;
@property (weak) id <XCUIApplicationMonitor> applicationMonitor;

/* class methods */
+ (id)sharedSession;
+ (void)setSharedSession:(id)session;
+ (double)IDEConnectionTimeout;
+ (void)daemonMediatedSessionForSessionIdentifier:(id)identifier daemonSession:(id)session delegate:(id)delegate completion:(id /* block */)completion;
+ (id)exportedCapabilities;

/* instance methods */
- (void)testBundleWillStart:(id)start;
- (void)testSuiteWillStart:(id)start;
- (void)testSuite:(id)suite didRecordSkipWithDescription:(id)description sourceCodeContext:(id)context;
- (void)testSuite:(id)suite didRecordIssue:(id)issue;
- (void)testSuite:(id)suite didRecordExpectedFailure:(id)failure;
- (void)testSuiteDidFinish:(id)finish;
- (void)testCaseWillStart:(id)start;
- (void)testCase:(id)_case didRecordSkipWithDescription:(id)description sourceCodeContext:(id)context;
- (void)testCasePlaceholder:(id)placeholder isUnavailableWithReason:(id)reason;
- (void)testCaseDidFinish:(id)finish;
- (void)testCase:(id)_case didRecordIssue:(id)issue;
- (void)testCase:(id)_case didRecordExpectedFailure:(id)failure;
- (void)_context:(id)_context willStartActivity:(id)activity;
- (void)_context:(id)_context didFinishActivity:(id)activity;
- (void)testBundleDidFinish:(id)finish;
- (id)suiteReporterForSuite:(id)suite;
- (id)currentTestContainer;
- (id)_IDE_processWithBundleID:(id)id path:(id)path pid:(id)pid crashedUnderSymbol:(id)symbol;
- (id)_IDE_stopTrackingProcessWithToken:(id)token;
- (id)_IDE_processWithToken:(id)token exitedWithStatus:(id)status;
- (id)_IDE_startExecutingTestPlanWithProtocolVersion:(id)version;
- (id)_IDE_fetchParallelizableTestIdentifiers;
- (id)_IDE_fetchAllTestIdentifiers;
- (id)_IDE_enumerateTests:(id)tests;
- (void)_debugLogCIState;
- (id)_IDE_executeTestsWithIdentifiersToRun:(id)run identifiersToSkip:(id)skip;
- (id)_IDE_shutdown;
- (void)reportBootstrappingFailure:(id)failure completion:(id /* block */)completion;
- (void)reportTestWithIdentifier:(id)identifier didExceedExecutionTimeAllowance:(double)allowance;
- (void)reportDidBeginExecutingTestPlan;
- (void)reportInitializationForUITestingFinishedWithError:(id)error;
- (void)reportDidFinishExecutingTestPlanWithCompletion:(id /* block */)completion;
- (void)reportStallOnMainThreadInTestCase:(id)_case file:(id)file line:(unsigned long long)line;
- (void)reportSelfDiagnosisIssue:(id)issue description:(id)description;
- (void)logDebugMessage:(id)message;
- (void)didFinishWritingAttachmentWithMetadata:(id)metadata;
- (id)initWithTransport:(id)transport delegate:(id)delegate;
- (void)flushOutgoingMessagesWithIDEConfirmationTimeout:(double)timeout;

@end

#endif /* XCTRunnerIDESession_h */
