//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTReportingSessionTestContainer_Protocol_h
#define XCTReportingSessionTestContainer_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTReportingSessionTestContainer <NSObject>

@required

/* required instance methods */
- (id)reportSuiteStartedWithName:(id)name atDate:(id)date traits:(id)traits;
- (id)reportSuiteStartedWithIdentifier:(id)identifier atDate:(id)date traits:(id)traits;
- (id)reportTestStartedWithName:(id)name isParameterized:(_Bool)parameterized argumentIDs:(id)ids atDate:(id)date iteration:(long long)iteration traits:(id)traits;
- (id)reportTestStartedWithIdentifier:(id)identifier atDate:(id)date testCaseRunConfiguration:(id)configuration traits:(id)traits;

@optional

@end

#endif /* XCTReportingSessionTestContainer_Protocol_h */
