//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTRunnerDaemonSession_h
#define XCTRunnerDaemonSession_h
@import Foundation;
@import UIKit;
#import <TargetConditionals.h>
#if !TARGET_OS_TV
@import CoreLocation;
#endif

#include "XCTMessagingChannel_RunnerToDaemon-Protocol.h"
#include "XCTRemoteSignpostListenerProxy-Protocol.h"
#include "XCTRunnerDaemonSessionUIAutomationDelegate-Protocol.h"
#include "XCTSignpostListener-Protocol.h"

@class NSMutableDictionary, NSObject, NSString, NSXPCConnection, XCTCapabilities;
@protocol OS_dispatch_queue, XCUIAXNotificationHandling, XCUIApplicationPlatformServicesProviderDelegate;

@interface XCTRunnerDaemonSession : NSObject <XCTRunnerDaemonSessionUIAutomationDelegate, XCTRemoteSignpostListenerProxy>

@property (readonly) NSObject<OS_dispatch_queue> *queue;
@property (retain) NSMutableDictionary *invalidationHandlers;
@property (readonly) NSXPCConnection *connection;
@property (readonly) id <XCTMessagingChannel_RunnerToDaemon> daemonProxy;
@property (readonly) XCTCapabilities *remoteInterfaceCapabilities;
@property (readonly) _Bool supportsPostingTelemetryData;
@property (weak) id <XCUIApplicationPlatformServicesProviderDelegate> platformApplicationServicesProviderDelegate;
@property (weak) id <XCUIAXNotificationHandling> axNotificationHandler;
@property (readonly) _Bool useLegacyEventCoordinateTransformationPath;
@property (readonly) _Bool usePointTransformationsForFrameConversions;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) _Bool supportsSignpostListening;
@property (weak) id <XCTSignpostListener> signpostListener;

/* class methods */
+ (id)testmanagerdServiceName;
+ (id)connectionForInitiatingSharedSession;
+ (id)sharedSessionPromiseAndImplicitlyInitiateSession:(_Bool)session;
+ (instancetype)sharedSession;
+ (instancetype)sharedSessionIfInitiated;
+ (void)initiateSharedSessionWithCompletion:(id /* block */)completion;
+ (void)initiateSessionWithCompletion:(id /* block */)completion;
+ (void)sessionWithConnection:(id)connection completion:(id /* block */)completion;
+ (void)capabilitiesForDaemonConnection:(id)connection completion:(id /* block */)completion;
+ (id)capabilities;
+ (void)registerCapabilitiesForDaemonConnection:(id)connection completion:(id /* block */)completion;

/* instance methods */
- (void)dealloc;
- (id)initWithConnection:(id)connection remoteInterfaceCapabilities:(id)capabilities;
- (void)_reportInvalidation;
- (id)registerInvalidationHandler:(id /* block */)handler;
- (void)unregisterInvalidationHandlerWithToken:(id)token;
- (void)_XCT_receivedAccessibilityNotification:(int)notification fromElement:(id)element payload:(id)payload;
- (void)requestIDEConnectionTransportForSessionIdentifier:(id)identifier reply:(id /* block */)reply;
- (void)requestSpindumpWithSpecification:(id)specification completion:(id /* block */)completion;
- (void)requestTailspinWithRequest:(id)request completion:(id /* block */)completion;
- (void)requestDTServiceHubConnectionWithReply:(id /* block */)reply;
- (void)postTelemetryData:(id)data reply:(id /* block */)reply;
- (void)registerForSignpostsFromSubsystem:(id)subsystem category:(id)category intervalTimeout:(double)timeout reply:(id /* block */)reply;
- (void)_XCT_receivedSignpost:(id)signpost withToken:(id)token;
- (void)unregisterForSignpostsWithToken:(id)token;

// Since Xcode 14.3
- (void)launchApplicationWithPath:(NSString *)path
                          bundleID:(NSString *)bundleID
                         arguments:(NSArray *)arguments
                       environment:(NSDictionary *)environment
                        completion:(void (^)(_Bool, NSError *))completion;
- (void)openURL:(NSURL *)url usingApplication:(NSString *)application completion:(void (^)(_Bool, NSError *))completion;
- (void)openDefaultApplicationForURL:(NSURL *)url completion:(void (^)(_Bool, NSError *))completion;
#if !TARGET_OS_TV // tvOS does not provide relevant APIs
- (void)setSimulatedLocation:(CLLocation *)location completion:(void (^)(_Bool, NSError *))completion;
- (void)getSimulatedLocationWithReply:(void (^)(CLLocation *, NSError *))reply;
- (void)clearSimulatedLocationWithReply:(void (^)(_Bool, NSError *))reply;
@property (readonly) _Bool supportsLocationSimulation;
#endif

// Since Xcode 15.0-beta1
- (void)stopScreenRecordingWithUUID:(NSUUID *)uuid
                          withReply:(void (^)(NSError *))reply;
- (void)startScreenRecordingWithRequest:(id /* XCTScreenRecordingRequest */)request
                              withReply:(void (^)(id /* XCTAttachmentFutureMetadata */, NSError *))reply;
- (_Bool)supportsScreenRecording;
- (_Bool)preferScreenshotsOverScreenRecordings;

@end

#endif /* XCTRunnerDaemonSession_h */
