//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTReportingSession_h
#define XCTReportingSession_h
@import Foundation;
@import UIKit;

#include "XCTReportingSessionConfiguration-Protocol.h"
#include "XCTReportingSessionIssueReporter-Protocol.h"
#include "XCTReportingSessionTestContainer-Protocol.h"
#include "_TtC10XCTestCore19XCTReportingContext.h"

@class NSObject, NSString, NSUUID, XCTReportingContext;

@interface XCTReportingSession : NSObject <XCTReportingSessionTestContainer, XCTReportingSessionIssueReporter> {
    /* instance variables */
     id uuid;
     id testableUUID;
}

@property (nonatomic, readonly) XCTReportingContext *context;
@property (nonatomic, readonly) id <XCTReportingSessionConfiguration> configuration;
@property (nonatomic, readonly) id <XCTReportingSessionIssueReporter> issueReporter;
@property (nonatomic, copy) NSString *aggregateStatus;

/* class methods */
+ (void)beginReportingSessionWithIdentifier:(NSUUID *)identifier completion:(id /* block */)completion;

/* instance methods */
- (void)updateAggregateStatusFor:(id)_for;
- (id)initWithIDEProxy:(id)ideproxy testConfiguration:(id)configuration publisher:(id)publisher;
- (void)reportStarted;
- (void)finishWithCompletion:(id /* block */)completion;
- (void)reportIssue:(id)issue atDate:(id)date;
- (void)reportPlanData:(id)data;
- (id)reportSuiteStartedWithName:(id)name atDate:(id)date;
- (id)reportSuiteStartedWithName:(id)name atDate:(id)date traits:(id)traits;
- (id)reportSuiteStartedWithIdentifier:(id)identifier atDate:(id)date traits:(id)traits;
- (id)reportTestStartedWithName:(id)name atDate:(id)date iteration:(long long)iteration;
- (id)reportTestStartedWithName:(id)name isParameterized:(_Bool)parameterized argumentIDs:(id)ids atDate:(id)date iteration:(long long)iteration traits:(id)traits;
- (id)reportTestStartedWithIdentifier:(id)identifier atDate:(id)date testCaseRunConfiguration:(id)configuration traits:(id)traits;
- (id)init;

@end

#endif /* XCTReportingSession_h */
