//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTRuntimeDiagnosticsPolicy_h
#define XCTRuntimeDiagnosticsPolicy_h
@import Foundation;
@import UIKit;

@class NSObject, NSString, XCTRuntimeIssueDetectionPolicy;

@interface XCTRuntimeDiagnosticsPolicy : NSObject <NSSecureCoding>

@property (readonly) _Bool isDefault;
@property (readonly) XCTRuntimeIssueDetectionPolicy *mainThreadCheckerDetectionPolicy;
@property (readonly) XCTRuntimeIssueDetectionPolicy *threadPerformanceCheckerRuntimeIssueDetectionPolicy;
@property (readonly) XCTRuntimeIssueDetectionPolicy *otherRuntimeIssuesDetectionPolicy;
@property (readonly) NSString *checkedAllocationsOption;

/* class methods */
+ (id)defaultRuntimeDiagnosticsPolicy;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)description;
- (id)initWithDictionary:(id)dictionary;
- (id)dictionaryRepresentation;
- (_Bool)isEqual:(id)equal;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* XCTRuntimeDiagnosticsPolicy_h */
