//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTRemoteSignpostListenerProxy_Protocol_h
#define XCTRemoteSignpostListenerProxy_Protocol_h
@import Foundation;
@import UIKit;

#include "XCTSignpostListener-Protocol.h"

@protocol XCTRemoteSignpostListenerProxy <NSObject>

@required

@property (readonly) _Bool supportsSignpostListening;
@property (weak) id <XCTSignpostListener> signpostListener;

/* required instance methods */
- (void)registerForSignpostsFromSubsystem:(id)subsystem category:(id)category intervalTimeout:(double)timeout reply:(id /* block */)reply;
- (void)unregisterForSignpostsWithToken:(id)token;

@optional

@end

#endif /* XCTRemoteSignpostListenerProxy_Protocol_h */
