//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTRunnerAutomationSession_Protocol_h
#define XCTRunnerAutomationSession_Protocol_h
@import Foundation;
@import UIKit;

#include "XCTElementSnapshotAttributeDataSource-Protocol.h"

@class XCTCapabilities;

@protocol XCTRunnerAutomationSession <XCTElementSnapshotAttributeDataSource>

@required

@property (readonly) XCTCapabilities *remoteInterfaceCapabilities;
@property (readonly) _Bool supportsFetchingAttributesForElement;
@property (readonly) _Bool supportsMainRunLoopIdleNotifications;
@property (readonly) _Bool supportsAnimationsIdleNotifications;
@property (readonly) _Bool isMacCatalyst;
@property (readonly) _Bool supportsMallocStackLogging;

/* required instance methods */
- (id)matchesForQuery:(id)query error:(id *)error;
- (void)notifyWhenMainRunLoopIsIdle:(id /* block */)idle;
- (void)notifyWhenAnimationsAreIdle:(id /* block */)idle;
- (void)setMallocStackLoggingWithMode:(int)mode reply:(id /* block */)reply;
- (void)detectRuntimeIssues;

@optional

@end

#endif /* XCTRunnerAutomationSession_Protocol_h */
