//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTRepetitionPolicy_h
#define XCTRepetitionPolicy_h
@import Foundation;
@import UIKit;

@class NSObject;

@interface XCTRepetitionPolicy : NSObject <NSSecureCoding>

@property (readonly) long long mode;
@property (readonly) long long maximumIterations;
@property (readonly) _Bool repeatInNewRunnerProcess;
@property (readonly) _Bool isDefault;

/* class methods */
+ (id)defaultRepetitionPolicy;
+ (id)stringFromRepetitionMode:(long long)mode;
+ (long long)modeFromString:(id)string;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithRepetitionMode:(long long)mode maximumIterations:(long long)iterations repeatInNewRunnerProcess:(_Bool)process;
- (id)initUntilFailureWithMaximumIterations:(long long)iterations repeatInNewRunnerProcess:(_Bool)process;
- (id)initRetryOnFailureWithMaximumIterations:(long long)iterations repeatInNewRunnerProcess:(_Bool)process;
- (id)initWithFixedIterations:(long long)iterations repeatInNewRunnerProcess:(_Bool)process;
- (id)initWithDictionary:(id)dictionary;
- (id)description;
- (id)dictionaryRepresentation;
- (_Bool)shouldRepeatWithTestFailure:(_Bool)failure iteration:(long long)iteration;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* XCTRepetitionPolicy_h */
