//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTRunnerDaemonSessionUIAutomationDelegate_Protocol_h
#define XCTRunnerDaemonSessionUIAutomationDelegate_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCUIAXNotificationHandling, XCUIApplicationPlatformServicesProviderDelegate;

@protocol XCTRunnerDaemonSessionUIAutomationDelegate <NSObject>

@required

@optional

@property (weak) id <XCUIApplicationPlatformServicesProviderDelegate> platformApplicationServicesProviderDelegate;
@property (weak) id <XCUIAXNotificationHandling> axNotificationHandler;
@property (readonly) _Bool useLegacyEventCoordinateTransformationPath;
@property (readonly) _Bool usePointTransformationsForFrameConversions;

/* optional instance methods */
- (void)requestBackgroundAssertionForPID:(int)pid reply:(id /* block */)reply;
- (void)finishInitializationForUIAutomation;
- (void)daemonDidUpdatePID:(int)pid forApplicationWithBundleID:(id)id andState:(unsigned long long)state;
- (void)receivedAccessibilityNotification:(int)notification fromElement:(id)element payload:(id)payload;

@end

#endif /* XCTRunnerDaemonSessionUIAutomationDelegate_Protocol_h */
