//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTRuntimeIssueDetectionPolicy_h
#define XCTRuntimeIssueDetectionPolicy_h
@import Foundation;
@import UIKit;

@class NSObject;

@interface XCTRuntimeIssueDetectionPolicy : NSObject <NSSecureCoding>

@property (readonly, getter=isDetectionEnabled) _Bool detectionEnabled;
@property (readonly) long long severity;
@property (readonly) _Bool isDefault;

/* class methods */
+ (id)defaultRuntimeIssueDetectionPolicy;
+ (id)stringFromSeverity:(long long)severity;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithDetectionEnabled:(_Bool)enabled severity:(long long)severity;
- (id)initWithDetectionEnabled:(_Bool)enabled;
- (id)initWithDictionary:(id)dictionary;
- (id)description;
- (_Bool)isEqual:(id)equal;
- (_Bool)isEqualToPolicy:(id)policy;
- (unsigned long long)hash;
- (id)dictionaryRepresentation;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;

@end

#endif /* XCTRuntimeIssueDetectionPolicy_h */
