//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTSkippedTestContext_h
#define XCTSkippedTestContext_h
@import Foundation;
@import UIKit;

@class NSObject, NSString, XCTSourceCodeContext;

@interface XCTSkippedTestContext : NSObject

@property (readonly, copy) NSString *summary;
@property (readonly, copy) NSString *explanation;
@property (readonly, copy) NSString *evaluatedExpression;
@property (readonly, copy) NSString *message;
@property (readonly) XCTSourceCodeContext *sourceCodeContext;
@property (readonly) _Bool isFromXCTSkip;

/* class methods */
+ (id)skippedTestContextWithExceptionPointer:(id)pointer evaluatedExpression:(id)expression message:(id)message sourceCodeContext:(id)context;

/* instance methods */
- (id)initWithExplanation:(id)explanation evaluatedExpression:(id)expression message:(id)message sourceCodeContext:(id)context isFromXCTSkip:(_Bool)xctskip;
- (id)initWithExplanation:(id)explanation evaluatedExpression:(id)expression message:(id)message sourceCodeContext:(id)context;
- (id)initWithExpectedValue:(_Bool)value evaluatedExpression:(id)expression message:(id)message sourceCodeContext:(id)context;
- (id)initWithException:(id)exception evaluatedExpression:(id)expression message:(id)message sourceCodeContext:(id)context;
- (id)initWithCurrentExceptionAndEvaluatedExpression:(id)expression message:(id)message sourceCodeContext:(id)context;
- (id)initWithError:(id)error evaluatedExpression:(id)expression message:(id)message sourceCodeContext:(id)context;
- (id)initWithNonSkipError:(id)error;

@end

#endif /* XCTSkippedTestContext_h */
