//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTSourceCodeContext_h
#define XCTSourceCodeContext_h
#import <XCTest/XCTSourceCodeContext.h>
@import Foundation;
@import UIKit;

@class NSArray, NSObject, XCTBacktrace, XCTSourceCodeLocation;

@interface XCTSourceCodeContext (FBXCTestPrivate)

@property (retain) XCTBacktrace *backtrace;
@property (readonly) _Bool needsSymbolication;

/* class methods */
+ (id)sourceCodeFramesFromCallStackReturnAddresses:(id)addresses;
+ (id)sourceCodeFramesFromUUIDsAndOffsets:(id)offsets;
+ (id)sourceCodeContextWithCallStackAddresses:(id)addresses emphasizedSymbolName:(id)name;
+ (id)sourceCodeContextWithBacktrace:(id)backtrace;
+ (id)sourceCodeContextWithUUIDsAndOffsets:(id)offsets emphasizedSymbolName:(id)name;
+ (id)preferredSourceCodeLocationForSourceCodeFrames:(id)frames emphasizedSymbolName:(id)name;
+ (id)_emphasizedImageNamesForSourceLocationInference;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (_Bool)symbolicateWithSymbolicationService:(id)service error:(id *)error;

@end

#endif /* XCTSourceCodeContext_h */
