//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTScreenCapturePolicy_h
#define XCTScreenCapturePolicy_h
@import Foundation;
@import UIKit;

@class NSObject;

@interface XCTScreenCapturePolicy : NSObject <NSSecureCoding>

@property (readonly, nonatomic) long long captureFormat;
@property (readonly, nonatomic) long long attachmentLifetime;

/* class methods */
+ (id)defaultPolicy;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithCaptureFormat:(long long)format attachmentLifetime:(long long)lifetime;
- (id)initWithDictionary:(id)dictionary;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;

@end

#endif /* XCTScreenCapturePolicy_h */
