//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTSourceCodeLocation_h
#define XCTSourceCodeLocation_h
#import <XCTest/XCTSourceCodeContext.h>
@import Foundation;
@import UIKit;

@class NSObject, NSString, NSURL;

@interface XCTSourceCodeLocation (FBXCTestPrivate)

@property (readonly) NSString *filePath;

/* class methods */
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)description;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;

@end

#endif /* XCTSourceCodeLocation_h */
