//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTSignpostListener_Protocol_h
#define XCTSignpostListener_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTSignpostListener <NSObject>

@required

/* required instance methods */
- (id)registerForSignpostsFromSubsystem:(id)subsystem category:(id)category intervalTimeout:(double)timeout error:(id *)error handler:(id /* block */)handler;
- (void)unregisterForSignpostsWithToken:(id)token;
- (void)receivedSignpost:(id)signpost withToken:(id)token;

@optional

@end

#endif /* XCTSignpostListener_Protocol_h */
