//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTTestIdentifier_h
#define XCTTestIdentifier_h
@import Foundation;
@import UIKit;

@class NSArray, NSObject, NSString;

@interface XCTTestIdentifier : NSObject <NSCopying, NSSecureCoding>

@property (readonly) _Bool isContainer;
@property (readonly) _Bool isLeaf;
@property (readonly) _Bool isSwiftMethod;
@property (readonly) _Bool representsBundle;
@property (readonly) _Bool usesClassAndMethodSemantics;
@property (readonly) NSString *displayName;
@property (readonly) NSString *identifierString;
@property (readonly) NSString *legacyClassAndMethodStringRepresentation;
@property (readonly) XCTTestIdentifier *parentIdentifier;
@property (readonly) NSString *firstComponent;
@property (readonly) NSString *lastComponent;
@property (readonly) NSString *lastComponentDisplayName;
@property (readonly) NSArray *displayNameComponents;
@property (readonly) XCTTestIdentifier *firstComponentIdentifier;
@property (readonly) NSArray *argumentIDs;
@property (readonly) XCTTestIdentifier *swiftMethodCounterpart;
@property (readonly) XCTTestIdentifier *objcMethodCounterpart;
@property (readonly) XCTTestIdentifier *legacyEncodingCounterpart;
@property (readonly) XCTTestIdentifier *identifierWithAncestorSuiteContext;
@property (readonly) XCTTestIdentifier *stagedIdentifier;
@property (readonly) _Bool encodingShouldIncludeLegacyKeys;
@property (readonly) unsigned long long options;
@property (readonly) unsigned long long componentCount;
@property (readonly) NSArray *components;

/* class methods */
+ (id)containerIdentifierWithComponent:(id)component;
+ (id)containerIdentifierWithComponents:(id)components;
+ (id)leafIdentifierWithComponents:(id)components;
+ (id)identifierForClass:(Class)_class;
+ (id)bundleIdentifier;
+ (id)allocWithZone:(struct _NSZone *)zone;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)description;
- (id)debugDescription;
- (id)debugQuickLookObject;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)_identifierString;
- (id)childIdentifierWithComponent:(id)component isContainer:(_Bool)container;
- (id)childIdentifierWithComponent:(id)component isContainer:(_Bool)container isSwiftMethod:(_Bool)method;
- (id)childIdentifierWithArgumentIDs:(id)ids;
- (id)childIdentifierWithLastComponentOf:(id)of;
- (id)childIdentifierWithArgumentIDsFromRunConfiguration:(id)configuration;
- (_Bool)isAncestorOfTestIdentifier:(id)identifier;
- (id)identifierWithAncestorSuiteIdentifier:(id)identifier;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithComponents:(id)components isContainer:(_Bool)container isSwiftMethod:(_Bool)method;
- (id)initWithComponents:(id)components isContainer:(_Bool)container;
- (id)initWithComponents:(id)components argumentIDs:(id)ids;
- (id)initWithClassAndMethodComponents:(id)components;
- (id)initWithClassName:(id)name;
- (id)initWithStringRepresentation:(id)representation;
- (id)initWithStringRepresentation:(id)representation preserveModulePrefix:(_Bool)prefix;
- (id)initWithSwiftTestingStringRepresentation:(id)representation;
- (id)initWithComponents:(id)components argumentIDs:(id)ids options:(unsigned long long)options;
- (id)componentAtIndex:(unsigned long long)index;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (Class)classForCoder;

@end

#endif /* XCTTestIdentifier_h */
