//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTTagSelection_h
#define XCTTagSelection_h
@import Foundation;
@import UIKit;

@class NSObject, NSSet;

@interface XCTTagSelection : NSObject <NSSecureCoding, NSCopying>

@property (readonly, copy) NSSet *tags;
@property (readonly) long long selectionMode;
@property (readonly) _Bool includeXCTests;
@property (readonly) _Bool isEmpty;

/* class methods */
+ (id)emptyTagSelection;
+ (long long)modeFromString:(id)string;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)initWithTags:(id)tags selectionMode:(long long)mode includeXCTests:(_Bool)xctests;
- (id)initWithTags:(id)tags selectionMode:(long long)mode;
- (id)description;
- (id)modeString;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)dictionary;
- (id)copyWithZone:(struct _NSZone *)zone;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* XCTTagSelection_h */
