//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTTestIdentifierSet_h
#define XCTTestIdentifierSet_h
@import Foundation;
@import UIKit;

#include "NSFastEnumeration-Protocol.h"
@class NSArray, NSDictionary, NSObject, XCTTestIdentifier;

@interface XCTTestIdentifierSet : NSObject <NSCopying, NSFastEnumeration, NSSecureCoding>

@property (readonly) XCTTestIdentifier *anyTestIdentifier;
@property (readonly) _Bool isEmpty;
@property (readonly) NSArray *sortedIdentifiers;
@property (readonly) NSDictionary *testIdentifiersGroupedByFirstComponentIdentifier;
@property (readonly) _Bool containsOnlyClassAndMethodIdentifiers;
@property (readonly) unsigned long long count;

/* class methods */
+ (id)emptyTestIdentifierSet;
+ (id)setByMergingTestIdentifierSets:(id)sets;
+ (id)allocWithZone:(struct _NSZone *)zone;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (void)enumerateTestIdentifiersUsingBlock:(id /* block */)block;
- (id)setByApplyingBlock:(id /* block */)block;
- (id)setByAddingTestIdentifiersFromSet:(id)set;
- (id)setByAddingSwiftCounterparts;
- (id)builder;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithTestIdentifier:(id)identifier;
- (id)initWithArray:(id)array;
- (id)initWithSet:(id)set;
- (id)initWithTestIdentifiers:(const id *)identifiers count:(unsigned long long)count;
- (id)init;
- (_Bool)containsTestIdentifier:(id)identifier;
- (_Bool)containsTestIdentifier:(id)identifier includingParents:(_Bool)parents;
- (_Bool)isSubsetOfTestIdentifierSet:(id)set;
- (id)description;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)countByEnumeratingWithState:(struct { unsigned long long x0; id *x1; unsigned long long *x2; unsigned long long x3[5]; } *)state objects:(id *)objects count:(unsigned long long)count;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (Class)classForCoder;

@end

#endif /* XCTTestIdentifierSet_h */
