//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTTestSelection_h
#define XCTTestSelection_h
@import Foundation;
@import UIKit;

@class NSObject, XCTTagSelection, XCTTestIdentifierSet;

@interface XCTTestSelection : NSObject <NSSecureCoding, NSCopying>

@property (copy) XCTTestIdentifierSet *identifiersToRun;
@property (copy) XCTTestIdentifierSet *identifiersToSkip;
@property (copy) XCTTagSelection *tagsToRun;
@property (copy) XCTTagSelection *tagsToSkip;

/* class methods */
+ (id)emptyTestSelection;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)description;
- (_Bool)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (unsigned long long)hash;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;

@end

#endif /* XCTTestSelection_h */
