//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTWaiterManager_Protocol_h
#define XCTWaiterManager_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCTWaiterManager

@required

/* required instance methods */
- (void)waiter:(id)waiter willBeginWaitingForWait:(id)wait;
- (void)waiter:(id)waiter timedOutWhileWaitingForWait:(id)wait;
- (void)waiter:(id)waiter didFinishWaitingForWait:(id)wait;

@optional

@end

#endif /* XCTWaiterManager_Protocol_h */
