//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTWaiter_h
#define XCTWaiter_h
#import <XCTest/XCTWaiter.h>
@import Foundation;
@import UIKit;

#include "XCTWaiterManagement-Protocol.h"
#include "XCTWaiterManager-Protocol.h"
@class NSArray, NSMutableOrderedSet, NSObject, NSString, XCTWaiterWait;

@interface XCTWaiter (FBXCTestPrivate)


@property (weak) id <XCTWaiterManager> customManager;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id /* block */)stallHandler;
+ (void)setStallHandler:(id /* block */)handler;
+ (double)watchdogTimeoutSlop;
+ (void)setWatchdogTimeoutSlop:(double)slop;
+ (void)wait:(double)wait;
+ (long long)waitForExpectations:(id)expectations;
+ (long long)waitForExpectations:(id)expectations timeout:(double)timeout;
+ (long long)waitForExpectations:(id)expectations enforceOrder:(_Bool)order;
+ (long long)waitForExpectations:(id)expectations timeout:(double)timeout enforceOrder:(_Bool)order;

/* instance methods */
- (void)swift_waitForExpectations:(id)expectations timeout:(double)timeout enforceOrder:(_Bool)order completionHandler:(id /* block */)handler;
- (void)handleStalledWait:(id)wait after:(double)after;
- (void)handleStalledWait:(id)wait;
- (void)primitiveWait:(double)wait;
- (void)cancelPrimitiveWait;
- (void)cancelWaiting;
- (id)init;
- (long long)waitForExpectations:(id)expectations;
- (long long)waitForExpectations:(id)expectations timeout:(double)timeout;
- (long long)waitForExpectations:(id)expectations enforceOrder:(_Bool)order;
- (long long)waitForExpectations:(id)expectations timeout:(double)timeout enforceOrder:(_Bool)order;
- (_Bool)allowsNestedWaitersWithWait:(id)wait;
- (void)interruptWait:(id)wait forWaiter:(id)waiter;

@end

#endif /* XCTWaiter_h */
