//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCTWaiterWait_h
#define XCTWaiterWait_h
@import Foundation;
@import UIKit;

#include "XCTestExpectationDelegate-Protocol.h"

@class NSArray, NSObject, NSString;

@interface XCTWaiterWait : NSObject <XCTestExpectationDelegate> {
    /* instance variables */
    unsigned int _result:4;
    unsigned int _stalled:1;
    _Bool _enforceOrder;
    _Bool _synchronous;
    NSArray *_expectations;
    double _timeout;
    id /* block */ _interruptHandler;
    NSArray *_callStackReturnAddressesOfCaller;
    unsigned long long _threadIDOfCaller;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithExpectations:(id)expectations timeout:(double)timeout enforceOrder:(_Bool)order isSynchronous:(_Bool)synchronous;
- (void)didFulfillExpectation:(id)expectation;

@end

#endif /* XCTWaiterWait_h */
