//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUISystem_h
#define XCUISystem_h
#import <XCTest/XCUISystem.h>
@import Foundation;
@import UIKit;

@class NSArray, NSObject, XCUIDevice;
@protocol XCUIDevice;

@interface XCUISystem (FBXCTestPrivate)

@property (readonly, weak) id <XCUIDevice> device;
@property (readonly) NSArray *activeForegroundApplications;

/* instance methods */
- (id)initWithDevice:(id)device;

@end

#endif /* XCUISystem_h */
