//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIDeviceEventAndStateInterface_Protocol_h
#define XCUIDeviceEventAndStateInterface_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCUIDeviceEventAndStateInterface <NSObject>

@required

@property (readonly) _Bool supportsAppearanceMode;
@property (readonly) _Bool supportsLocationSimulation;
@property (readonly) _Bool supportsHandGestures;
@property (readonly) _Bool supportsUserPresence;

/* required instance methods */
- (void)performDeviceEvent:(id)event completion:(id /* block */)completion;
- (void)updateDeviceOrientation:(long long)orientation completion:(id /* block */)completion;
- (void)getDeviceOrientationWithCompletion:(id /* block */)completion;
- (void)updateAppearanceMode:(long long)mode completion:(id /* block */)completion;
- (void)getAppearanceModeWithReply:(id /* block */)reply;
- (void)getInterfaceOrientationWithReply:(id /* block */)reply;
- (void)getSimulatedLocationWithReply:(id /* block */)reply;
- (void)setSimulatedLocation:(id)location completion:(id /* block */)completion;
- (void)clearSimulatedLocationWithReply:(id /* block */)reply;
- (void)hasHardwareButton:(long long)button completion:(id /* block */)completion;
- (void)clearUserPresenceAssertionWithReply:(id /* block */)reply;
- (void)acquireUserPresenceAssertionWithReply:(id /* block */)reply;
- (void)continuityDisplayIsActiveWithCompletion:(id /* block */)completion;

@optional

@end

#endif /* XCUIDeviceEventAndStateInterface_Protocol_h */
