//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIApplication_h
#define XCUIApplication_h
#import <XCTest/XCUIApplication.h>
@import Foundation;
@import UIKit;

#include "XCTRunnerAutomationSession-Protocol.h"
#include "XCUIElement.h"
#include "XCUIIssueDiagnosticsProviding-Protocol.h"

@class NSArray, NSDictionary, NSString, XCAccessibilityElement, XCApplicationQuery, XCUIApplicationImpl, XCUIApplicationOpenRequest, XCUIDevice, XCUIElement;
@protocol XCUIDevice;

@interface XCUIApplication (FBXCTestPrivate)

@property (retain) XCUIApplicationOpenRequest *lastLaunchRequest;
@property (retain) XCApplicationQuery *applicationQuery;
@property (readonly) XCUIElement *keyboard;
@property unsigned long long generation;
@property (nonatomic) unsigned int currentInteractionOptions;
@property _Bool ancillary;
@property (readonly) _Bool backgroundInteractionAllowed;
@property (readonly) _Bool shouldBeCheckedForInterruptingElements;
@property (readonly) XCUIApplicationImpl *applicationImpl;
@property _Bool prefersPlatformLauncher;
@property (readonly) id <XCTRunnerAutomationSession> automationSession;
@property (readonly) id <XCUIDevice> device;
@property (readonly) id /*XCAccessibilityElement*/ accessibilityElement;
@property (nonatomic) int processID;
@property (readonly) NSString *bundleID;
@property (readonly) NSString *path;
@property (readonly) _Bool running;
@property (readonly) _Bool suspended;
@property (readonly) _Bool background;
@property (readonly) _Bool foreground;
@property (nonatomic) _Bool doesNotHandleUIInterruptions;
@property _Bool allowBackgroundInteraction;
@property (readonly) _Bool hasAutomationSession;
@property _Bool idleAnimationWaitEnabled;
@property (readonly) _Bool fauxCollectionViewCellsEnabled;
#if !TARGET_OS_TV && !TARGET_OS_WATCH
@property (readonly, nonatomic) UIInterfaceOrientation interfaceOrientation;
#endif
@property (nonatomic) unsigned long long crashBehavior;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)keyPathsForValuesAffectingIsApplicationStateKnown;
+ (id)keyPathsForValuesAffectingState;
+ (id)keyPathsForValuesAffectingRunning;
+ (id)keyPathsForValuesAffectingSuspended;
+ (id)keyPathsForValuesAffectingBackground;
+ (id)keyPathsForValuesAffectingForeground;

/* instance methods */
- (id)initWithElementQuery:(id)query;
- (id)initWithBundleIdentifier:(id)identifier device:(id)device;
- (id)initWithApplicationSpecifier:(id)specifier device:(id)device;
- (id)initWithApplicationSpecifier:(id)specifier device:(id)device error:(id *)error;
- (id)initPrivateWithPath:(id)path bundleID:(id)id;
- (void)commonInitWithApplicationSpecifier:(id)specifier device:(id)device;
- (unsigned long long)elementType;
- (_Bool)resolveOrRaiseTestFailure:(_Bool)failure error:(id *)error;
- (void)clearQuery;
- (id)query;
- (id)application;
- (id)currentProcess;
- (_Bool)exists;
- (void)resetAlertCount;
- (_Bool)isApplicationStateKnown;
- (id)_combinedLaunchArguments;
- (id)_combinedLaunchEnvironment;
- (void)launchWithoutAccessibility:(_Bool)accessibility;
- (void)_launchUsingXcode:(_Bool)xcode;
- (void)_launchUsingXcode:(_Bool)xcode withoutAccessibility:(_Bool)accessibility launchURL:(id)url;
- (void)_performWithInteractionOptions:(unsigned int)options block:(id /* block */)block;
- (void)_waitForQuiescence;
- (void)_waitForQuiescenceAsPreEvent:(_Bool)event;
- (_Bool)_waitForViewControllerViewDidDisappearWithTimeout:(double)timeout error:(id *)error;
- (id)viewDidAppearExpectationForViewControllerWithName:(id)name;
- (_Bool)setFauxCollectionViewCellsEnabled:(_Bool)enabled error:(id *)error;
- (void)dismissKeyboard;
- (id)diagnosticAttachmentsForError:(id)error;
- (unsigned long long)defaultCrashBehavior;
- (_Bool)isIdleAnimationWaitEnabled;

@end

#endif /* XCUIApplication_h */
