//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUICoordinate_h
#define XCUICoordinate_h
#import <TargetConditionals.h>
#if !TARGET_OS_TV // XCUICoordinate does not exist on tvOS's XCTest private framework
#import <XCTest/XCUICoordinate.h>
@import Foundation;
@import UIKit;

@class NSObject, XCUIElement;

@interface XCUICoordinate (FBXCTestPrivate)

@property (readonly) XCUIElement *element;
@property (readonly) XCUICoordinate *coordinate;
@property (readonly) CGVector normalizedOffset;
@property (readonly) CGVector pointsOffset;

/* instance methods */
- (void)clickForDuration:(double)duration;
- (void)_clickForDuration:(double)duration thenDragToCoordinate:(id)coordinate dragVelocity:(double)velocity;
- (void)forcePress;
- (void)pressWithPressure:(double)pressure duration:(double)duration;
- (void)hover;
- (void)click;
- (void)doubleClick;
- (void)rightClick;
- (void)swipeUp;
- (void)swipeDown;
- (void)swipeLeft;
- (void)swipeRight;
- (id)init;
- (id)initWithElement:(id)element normalizedOffset:(CGVector)offset;
- (id)initWithCoordinate:(id)coordinate pointsOffset:(CGVector)offset;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (id)device;
- (CGVector)_originIndependentOffset;
- (CGPoint)_userSpaceScreenPoint;

@end

#endif // !TARGET_OS_TV
#endif /* XCUICoordinate_h */
