//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIApplicationImpl_h
#define XCUIApplicationImpl_h
@import Foundation;
@import UIKit;

#include "XCUIApplicationImplReporter-Protocol.h"
#include "XCUIApplicationProcessDelegate-Protocol.h"
#include "XCUIIssueDiagnosticsProviding-Protocol.h"

@class NSObject, NSString, XCAccessibilityElement, XCUIApplicationProcess, XCUIDevice;
@protocol XCUIDevice;

@interface XCUIApplicationImpl : NSObject <XCUIApplicationProcessDelegate>

@property _Bool hasValidAlertCount;
@property _Bool previousOnDemandAutomationSessionRequestFailed;
@property int terminatingPID;
@property _Bool isTestDependency;
@property (retain) id <XCUIApplicationImplReporter> issueReporter;
@property (readonly, copy) NSString *path;
@property (readonly, copy) NSString *bundleID;
@property (nonatomic) int processID;
@property (nonatomic) unsigned long long state;
@property (readonly) _Bool running;
@property (readonly) _Bool suspended;
@property (readonly) _Bool background;
@property (readonly) _Bool foreground;
@property (readonly) _Bool activated;
@property (retain, nonatomic) XCUIApplicationProcess *currentProcess;
@property (readonly) id <XCUIIssueDiagnosticsProviding> diagnosticsProvider;
@property (readonly) id <XCUIDevice> device;
@property (readonly) id /*XCAccessibilityElement*/ accessibilityElement;
@property _Bool codeCoverageEnabled;
@property (readonly) unsigned long long alertCount;
@property (nonatomic) unsigned long long crashBehavior;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)keyPathsForValuesAffectingHasCurrentProcess;
+ (id)keyPathsForValuesAffectingState;
+ (id)keyPathsForValuesAffectingRunning;
+ (id)keyPathsForValuesAffectingSuspended;
+ (id)keyPathsForValuesAffectingBackground;
+ (id)keyPathsForValuesAffectingForeground;
+ (id)keyPathsForValuesAffectingActivated;
+ (id)keyPathsForValuesAffectingCurrentProcessAccessibilityActive;

/* instance methods */
- (id)initWithPath:(id)path bundleID:(id)id device:(id)device;
- (id)initWithPath:(id)path bundleID:(id)id device:(id)device isTestDependency:(_Bool)dependency;
- (id)initWithPath:(id)path bundleID:(id)id device:(id)device isTestDependency:(_Bool)dependency issueReporter:(id)reporter;
- (id)initWithPath:(id)path bundleID:(id)id;
- (id)compactDescription;
- (_Bool)hasCurrentProcess;
- (_Bool)waitForState:(unsigned long long)state timeout:(double)timeout;
- (void)resetAlertCount;
- (void)_awaitValidCurrentProcess;
- (void)serviceOpenRequest:(id)request;
- (void)_activate;
- (void)_activateForPlatform;
- (void)applicationProcessAutomationSessionRequestFailed:(id)failed;
- (_Bool)applicationProcessShouldRequestAutomationSession:(id)session;
- (_Bool)shouldDetectRuntimeIssues;
- (void)applicationProcessDidLoadAutomationSession:(id)session;
- (_Bool)shouldWaitForAutomationSessionWhenUsingPlatformLauncher:(_Bool)launcher;
- (void)_launchWithRequest:(id)request;
- (void)_waitForLaunchProgressWithToken:(id)token;
- (void)_launchUsingXcodeWithArguments:(id)arguments environment:(id)environment launchURL:(id)url;
- (void)_launchUsingPlatformWithArguments:(id)arguments environment:(id)environment launchURL:(id)url;
- (void)_waitForValidPID;
- (_Bool)currentProcessAccessibilityActive;
- (void)waitForAccessibilityActive;
- (id)_activationExpectation;
- (void)_waitOnActivationExpectation:(id)expectation;
- (void)terminate;
- (void)handleCrashUnderSymbol:(id)symbol;
- (_Bool)waitForViewControllerViewDidDisappearWithTimeout:(double)timeout error:(id *)error;
- (void)resetAuthorizationStatusForResource:(long long)resource;

@end

#endif /* XCUIApplicationImpl_h */
