//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIEventRecording_Protocol_h
#define XCUIEventRecording_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCUIEventRecording

@required

/* required instance methods */
- (void)recordTapElement:(id)element application:(id)application;
- (void)recordLongPressElement:(id)element application:(id)application;
- (void)recordDragElement:(id)element application:(id)application byCoordinates:(CGPoint)coordinates;
- (void)recordSetPickerValue:(id)value element:(id)element application:(id)application;
- (void)recordWaitForExistenceOfElement:(id)element application:(id)application;
- (void)recordKeyboardTypingString:(id)string inApp:(id)app;
- (void)recordTapCoordinate:(CGPoint)coordinate inApp:(id)app;
- (void)recordLongPressCoordinate:(CGPoint)coordinate inApp:(id)app;
- (void)recordLaunchApplicationWithBundleID:(id)id;
- (void)recordPressHomeButton;
- (void)recordComment:(id)comment;
- (void)recordFinishedWithError:(id)error;
- (void)recordKeyboardTypingString:(id)string applicationSnapshot:(id)snapshot;
- (void)recordTapCoordinate:(CGPoint)coordinate appSnapshot:(id)snapshot;
- (void)recordLongPressCoordinate:(CGPoint)coordinate appSnapshot:(id)snapshot;

@optional

@end

#endif /* XCUIEventRecording_Protocol_h */
