//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIApplicationProcess_h
#define XCUIApplicationProcess_h
@import Foundation;
@import UIKit;

#include "XCTElementSnapshotAttributeDataSource-Protocol.h"
#include "XCTRunnerAutomationSession-Protocol.h"
#include "XCUIApplicationProcessDelegate-Protocol.h"
#include "XCUIIssueDiagnosticsProviding-Protocol.h"

@class NSObject, NSString, XCAccessibilityElement, XCElementSnapshot, XCTFuture, XCUIDevice;
@protocol OS_dispatch_queue, XCUIDevice;

@interface XCUIApplicationProcess : NSObject <XCTElementSnapshotAttributeDataSource, XCUIIssueDiagnosticsProviding> {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_queue;
}

@property _Bool eventLoopHasIdled;
@property _Bool animationsHaveFinished;
@property (readonly) XCTFuture *automationSessionFuture;
@property (readonly, copy, nonatomic) NSString *path;
@property (readonly, copy, nonatomic) NSString *bundleID;
@property (nonatomic) int processID;
@property (readonly, getter=isProcessIDValid) _Bool processIDValid;
@property (nonatomic) unsigned long long applicationState;
@property unsigned int interactionOptions;
@property (readonly) _Bool shouldSkipPreEventQuiescence;
@property (readonly) _Bool shouldSkipPostEventQuiescence;
@property (readonly) _Bool running;
@property (readonly) _Bool suspended;
@property (readonly) _Bool background;
@property (readonly) _Bool foreground;
@property (nonatomic) _Bool accessibilityActive;
@property (retain) id token;
@property int exitCode;
@property _Bool hasExitCode;
@property _Bool hasCrashReport;
@property (nonatomic) _Bool mayTerminateOutOfBandWithoutCrashReport;
@property _Bool shouldContinueMonitoringAfterExit;
@property (retain, nonatomic) id <XCTRunnerAutomationSession> automationSession;
@property (readonly) id <XCTRunnerAutomationSession> automationSessionNonBlocking;
@property (retain) id/*XCElementSnapshot*/ lastSnapshot;
@property (readonly, copy) NSString *shortDescription;
@property (readonly, copy) id /*XCAccessibilityElement*/ accessibilityElement;
@property (readonly) unsigned long long alertCount;
@property (readonly) id <XCUIDevice> device;
@property (readonly) id <XCUIApplicationProcessDelegate> delegate;
@property (readonly) _Bool allowsRemoteAccess;
@property (readonly) _Bool supportsHostedViewCoordinateTransformations;
@property (readonly) _Bool usePointTransformationsForFrameConversions;
@property (readonly) _Bool hasBannerNotificationIsStickyAttribute;
@property (readonly) _Bool providesValuesForPrivilegedAttributes;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)keyPathsForValuesAffectingIsApplicationStateKnown;
+ (id)keyPathsForValuesAffectingRunning;
+ (id)keyPathsForValuesAffectingSuspended;
+ (id)keyPathsForValuesAffectingBackground;
+ (id)keyPathsForValuesAffectingForeground;
+ (id)keyPathsForValuesAffectingIsProcessIDValid;
+ (_Bool)automaticallyNotifiesObserversForKey:(id)key;
+ (id)keyPathsForValuesAffectingIsQuiescent;

/* instance methods */
- (id)initWithPath:(id)path bundleID:(id)id device:(id)device delegate:(id)delegate;
- (id)initWithBundleID:(id)id device:(id)device delegate:(id)delegate;
- (id)_queue_description;
- (void)_awaitKnownApplicationState;
- (_Bool)isApplicationStateKnown;
- (void)incrementAlertCount;
- (void)resetAlertCount;
- (void)_notifyWhenMainRunLoopIsIdle:(id /* block */)idle;
- (_Bool)_supportsAnimationsIdleNotifications;
- (void)_notifyWhenAnimationsAreIdle:(id /* block */)idle;
- (id)_makeQuiescenceExpectation;
- (void)waitForQuiescenceIncludingAnimationsIdle:(_Bool)idle;
- (void)waitForQuiescenceIncludingAnimationsIdle:(_Bool)idle isPreEvent:(_Bool)event;
- (void)waitForQuiescenceIncludingAnimationsIdle:(_Bool)idle usingActivity:(_Bool)activity isPreEvent:(_Bool)event;
- (void)_initiateQuiescenceChecksIncludingAnimationsIdle:(_Bool)idle;
- (_Bool)isQuiescent;
- (void)waitForAutomationSession;
- (id)_queue_automationSessionFuture;
- (void)acquireBackgroundAssertion;
- (_Bool)waitForViewControllerViewDidDisappearWithTimeout:(double)timeout error:(id *)error;
- (_Bool)terminate:(id *)terminate;
- (id)_underlyingDataSourceForElement:(id)element;
- (id)attributesForElement:(id)element attributes:(id)attributes error:(id *)error;
- (id)valuesForPrivilegedAttributes:(id)attributes forElement:(id)element error:(id *)error;
- (id)parameterizedAttribute:(id)attribute forElement:(id)element parameter:(id)parameter error:(id *)error;
- (_Bool)isMacCatalystForPID:(int)pid;
- (id)diagnosticAttachmentsForError:(id)error;

@end

#endif /* XCUIApplicationProcess_h */
