//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIRemoteSiriInterface_Protocol_h
#define XCUIRemoteSiriInterface_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCUIRemoteSiriInterface <NSObject>

@required

@property (readonly) _Bool supportsStartingSiriUIRequestWithAudioFileURL;
@property (readonly) _Bool supportsInjectingVoiceRecognitionAudioInputPaths;

/* required instance methods */
- (void)requestSiriEnabledStatus:(id /* block */)status;
- (void)startSiriUIRequestWithText:(id)text completion:(id /* block */)completion;
- (void)startSiriUIRequestWithAudioFileURL:(id)url completion:(id /* block */)completion;
- (void)injectAssistantRecognitionStrings:(id)strings completion:(id /* block */)completion;
- (void)injectVoiceRecognitionAudioInputPaths:(id)paths completion:(id /* block */)completion;

@optional

@end

#endif /* XCUIRemoteSiriInterface_Protocol_h */
