//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIRemoteAccessibilityInterface_Protocol_h
#define XCUIRemoteAccessibilityInterface_Protocol_h
@import Foundation;
@import UIKit;

@class XCTCapabilities;

@protocol XCUIRemoteAccessibilityInterface <NSObject>

@required

@property (readonly) XCTCapabilities *remoteInterfaceCapabilities;
@property (readonly) _Bool useLegacySnapshotPath;
@property (readonly) _Bool axNotificationsIncludeElement;

/* required instance methods */
- (_Bool)isAccessibilitySupported;
- (void)loadAccessibilityWithTimeout:(double)timeout reply:(id /* block */)reply;
- (void)unloadAccessibility:(id /* block */)accessibility;
- (void)registerForAccessibilityNotification:(int)notification reply:(id /* block */)reply;
- (void)unregisterForAccessibilityNotification:(int)notification registrationToken:(id)token reply:(id /* block */)reply;
- (void)performAccessibilityAction:(id)action onElement:(id)element value:(id)value reply:(id /* block */)reply;
- (void)snapshotForElement:(id)element attributes:(id)attributes parameters:(id)parameters reply:(id /* block */)reply;
- (void)requestSnapshotForElement:(id)element attributes:(id)attributes parameters:(id)parameters reply:(id /* block */)reply;
- (void)fetchSnapshotForElement:(id)element attributes:(id)attributes parameters:(id)parameters reply:(id /* block */)reply;
- (void)runAccessibilityAuditForElement:(id)element withConfiguration:(id)configuration reply:(id /* block */)reply;
- (void)fetchAttributes:(id)attributes forElement:(id)element reply:(id /* block */)reply;
- (void)setAttribute:(id)attribute value:(id)value element:(id)element reply:(id /* block */)reply;
- (void)fetchParameterizedAttribute:(id)attribute forElement:(id)element parameter:(id)parameter reply:(id /* block */)reply;
- (void)requestElementAtPoint:(CGPoint)point reply:(id /* block */)reply;
- (void)setAXTimeout:(double)axtimeout reply:(id /* block */)reply;
- (void)enableFauxCollectionViewCells:(id /* block */)cells;
- (void)setLocalizableStringsDataGatheringEnabled:(_Bool)enabled reply:(id /* block */)reply;

@optional

@end

#endif /* XCUIRemoteAccessibilityInterface_Protocol_h */
