//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIInterruptionMonitoring_Protocol_h
#define XCUIInterruptionMonitoring_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCUIInterruptionMonitoring <NSObject>

@required

@property _Bool didHandleUIInterruption;

/* required instance methods */
- (id)addInterruptionHandlerWithDescription:(id)description block:(id /* block */)block;
- (void)removeInterruptionHandlerWithIdentifier:(id)identifier;
- (_Bool)handleInterruptingElement:(id)element;

@optional

@end

#endif /* XCUIInterruptionMonitoring_Protocol_h */
