//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIXcodeApplicationManaging_Protocol_h
#define XCUIXcodeApplicationManaging_Protocol_h
@import Foundation;
@import UIKit;

#include "XCUIApplicationManaging-Protocol.h"

@protocol XCUIXcodeApplicationManaging <XCUIApplicationManaging>

@required

/* required instance methods */
- (void)openURL:(id)url processPath:(id)path bundleID:(id)id arguments:(id)arguments environmentVariables:(id)variables completion:(id /* block */)completion;
- (void)requestLaunchProgressForProcessWithToken:(id)token completion:(id /* block */)completion;
- (void)terminateProcessWithToken:(id)token completion:(id /* block */)completion;

@optional

@end

#endif /* XCUIXcodeApplicationManaging_Protocol_h */
