//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIScreen_h
#define XCUIScreen_h
#import <XCTest/XCUIScreen.h>
@import Foundation;
@import UIKit;

#include "XCUIScreenDataSource-Protocol.h"

@class NSObject, NSString, NSUUID, XCUIButtonConsole, XCUIDevice, XCUIKnobControl;
@protocol XCUIDevice;

@interface XCUIScreen (FBXCTestPrivate)

@property (retain, nonatomic) NSUUID *currentDiagnosticScreenRecordingUUID;
@property (readonly) _Bool isMainScreen;
@property (readonly, weak) id <XCUIDevice> device;
@property (readonly) id <XCUIScreenDataSource> screenDataSource;
@property (readonly) XCUIButtonConsole *buttonConsole;
@property (readonly) XCUIKnobControl *knobControl;
@property (readonly) long long displayID;
@property (readonly) double scale;
@property (readonly) CGRect bounds;
@property (readonly) unsigned long long traits;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)mainScreen;
+ (id)screens;

/* instance methods */
- (id)initWithDisplayID:(long long)id isMainScreen:(_Bool)screen device:(id)device screenDataSource:(id)source;
- (id)makeDiagnosticScreenshotAttachment;
- (void)startDiagnosticScreenRecordingWithCompletion:(id /* block */)completion;
- (void)stopDiagnosticRecordingWithCompletion:(id /* block */)completion;
- (_Bool)isEqual:(id)equal;
- (id)screenshot;
- (id)screenshotWithEncoding:(id)encoding options:(unsigned long long)options;
- (id)screenshotWithPreferredEncoding:(id)encoding rect:(CGRect)rect error:(id *)error;
- (id)screenshotWithPreferredEncoding:(id)encoding rect:(CGRect)rect options:(unsigned long long)options error:(id *)error;
- (id)screenshotAttachmentWithPreferredEncoding:(id)encoding rect:(CGRect)rect options:(unsigned long long)options error:(id *)error;

@end

#endif /* XCUIScreen_h */
