//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIDevice_h
#define XCUIDevice_h
#import <XCTest/XCUIDevice.h>
@import Foundation;
@import UIKit;

#include "XCUIAccessibilityInterface-Protocol.h"
#include "XCUIAlertMonitoring-Protocol.h"
#include "XCUIApplicationAutomationSessionProviding-Protocol.h"
#include "XCUIApplicationMonitor-Protocol.h"
#include "XCUIApplicationProcessManaging-Protocol.h"
#include "XCUIDeviceAutomationModeInterface-Protocol.h"
#include "XCUIDeviceDelayedAttachmentTransferSupportInterface-Protocol.h"
#include "XCUIDeviceEventAndStateInterface-Protocol.h"
#include "XCUIEventRecording-Protocol.h"
#include "XCUIInterruptionMonitoring-Protocol.h"
#include "XCUIRemoteDeviceRunner-Protocol.h"
#include "XCUIResetAuthorizationStatusOfProtectedResourcesInterface-Protocol.h"
#include "XCUIScreenDataSource-Protocol.h"
#include "XCUIXcodeApplicationManaging-Protocol.h"

@class NSError, NSObject, NSString, XCTContext, XCUIRemote, XCUILocation, XCUIScreen, XCUISiriService, XCUISystem;
@protocol XCTSignpostListener, XCUIDeviceDiagnostics;

@protocol XCUIEventSynthesizing <NSObject>
- (void)synthesizeEvent:(id)event completion:(void (^)(_Bool success, NSError *error))completion;
@end

@interface XCUIDevice (FBXCTestPrivate)


@property (retain, nonatomic) XCUIScreen *screenCurrentlyUsedForScreenRecording;
@property _Bool wasSystemAppActivated;
@property (readonly) NSString *descriptionIncludingName;
@property (readonly) id <XCTSignpostListener> signpostListener;
@property (retain) id <XCUIRemoteDeviceRunner> remoteRunner;
@property (retain) NSError *remoteRunnerError;
@property (readonly) XCUISiriService *siriService;
@property (retain, nonatomic) XCUILocation *location;
@property (nonatomic) long long appearance;
- (long long)appearanceMode;

/* class methods */
+ (void)initialize;
+ (_Bool)isMultiDeviceHost;
+ (id)localDevice;
+ (void)setLocalDevice:(id)device;
+ (instancetype)sharedDevice;

/* instance methods */
- (id)initLocalDeviceWithPlatform:(long long)platform;
- (id)initWithDiagnosticProvider:(id)provider;
- (_Bool)enableAutomationMode:(id *)mode;
- (id)diagnosticAttachmentsForError:(id)error;
- (_Bool)configuredForUITesting;
- (_Bool)performDeviceEvent:(id)event error:(id *)error;
- (_Bool)supportsPressureInteraction;
- (_Bool)supportsContinuityDisplay;
- (void)screensWithCompletion:(id /* block */)completion;
- (id)screensOrError:(id *)error;
- (id)mainScreenOrError:(id *)error;
- (void)mainScreenWithCompletion:(id /* block */)completion;
- (id)screenWithDisplayID:(long long)id orError:(id *)error;
- (id)screens;
- (id)mainScreen;
- (id)makeDiagnosticScreenshotAttachmentForDevice;
- (id)makeDiagnosticScreenshotAttachmentsForDevice;
- (void)startDiagnosticScreenRecordingWithCompletion:(id /* block */)completion;
- (void)stopDiagnosticScreenRecordingWithCompletion:(id /* block */)completion;
- (_Bool)isScreenRecordingActive;
- (_Bool)isScreenRecordingSupported;
- (void)isMultiDeviceScreenRecordingSupportedWithCompletion:(id /* block */)completion;
- (id)spindumpAttachmentForProcessID:(int)id error:(id *)error;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (id)description;
- (id)init;
- (void)_setOrientation:(long long)orientation;
- (_Bool)_isInTopLevelActivity;
- (void)didUpdateDeviceOrientation:(long long)orientation;
- (void)didUpdateInterfaceOrientation:(long long)orientation;
- (void)_clearSimulatedLocation;
- (void)_silentPressButton:(long long)button;
- (void)holdHomeButtonForDuration:(double)duration;
- (void)pressLockButton;
- (void)rotateDigitalCrown:(double)crown velocity:(double)velocity;
- (void)ensureSystemAppIsLoaded;
- (void)attachLocalizableStringsData;
- (_Bool)startHIDEventRecordingWithError:(id *)error;
- (_Bool)stopHIDEventRecordingAndSaveToURL:(id)url error:(id *)error;
- (_Bool)playBackHIDEventRecordingFromURL:(id)url error:(id *)error;
- (void)simulateUserPresent;
- (void)simulateUserNotPresent;
- (void)_simulateUserPresence:(_Bool)presence;
- (unsigned long long)_setModifiers:(unsigned long long)modifiers merge:(_Bool)merge beginPersistentState:(_Bool)state description:(id)description;
- (void)performWithKeyModifiers:(unsigned long long)modifiers block:(id /* block */)block;
- (void)remoteAutomationSessionDidDisconnect:(id)disconnect;
- (void)remoteRunnerDidUnexpectedlyDisconnectForSession:(id)session;
- (_Bool)exitRemoteRunnerWithError:(id *)error;
- (id)_runnerOrError:(id *)error;
- (void)waitForRemoteRunnerExit;
- (_Bool)isLocal;
- (long long)platform;
- (id)accessibilityInterface;
- (id)applicationMonitor;
- (id<XCUIEventSynthesizing>)eventSynthesizer;
- (id)eventRecorder;
- (id)platformApplicationManager;
- (id)xcodeApplicationManager;
- (id)deviceEventAndStateInterface;
- (id)applicationAutomationSessionProvider;
- (id)screenDataSource;
- (id)uniqueIdentifier;
- (_Bool)isSimulatorDevice;
- (id)remote;
- (id)interruptionMonitor;
- (id)alertMonitor;
- (id)resetAuthorizationStatusInterface;
- (id)diagnosticsProvider;
- (id)automationModeInterface;
- (id)delayedAttachmentTransferSupportInterface;
- (id)reportingContext;
- (id)name;
- (id)alias;
- (void)setAlias:(id)alias;

@end

#endif /* XCUIDevice_h */
