//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIApplicationOpenRequest_h
#define XCUIApplicationOpenRequest_h
@import Foundation;
@import UIKit;

@class NSArray, NSDictionary, NSObject, NSURL;

@interface XCUIApplicationOpenRequest : NSObject

@property _Bool activateIfRunning;
@property _Bool terminateIfRunning;
@property _Bool usePlatformLauncher;
@property _Bool disableAccessibility;
@property (copy) NSArray *launchArguments;
@property (copy) NSDictionary *environmentVariables;
@property (retain) NSURL *launchUrl;

/* class methods */
+ (id)launchRequestWithLaunchArguments:(id)arguments environmentVariables:(id)variables usePlatformLauncher:(_Bool)launcher;
+ (id)launchRequestWithLaunchArguments:(id)arguments environmentVariables:(id)variables launchURL:(id)url usePlatformLauncher:(_Bool)launcher disableAccessibility:(_Bool)accessibility;
+ (id)activationRequestWithLaunchArguments:(id)arguments environmentVariables:(id)variables usePlatformLauncher:(_Bool)launcher;
+ (id)activationRequestFromLaunchRequest:(id)request;

/* instance methods */

@end

#endif /* XCUIApplicationOpenRequest_h */
