//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUISiriService_h
#define XCUISiriService_h
#import <XCTest/XCUISiriService.h>
@import Foundation;
@import UIKit;

#include "XCUIRemoteSiriInterface-Protocol.h"

@class NSObject, NSString, XCUIApplication, XCUIDevice;
@protocol XCUIDevice;

@interface XCUISiriService (FBXCTestPrivate)

@property (readonly) XCUIApplication *siriApplication;
@property (readonly) _Bool supportsAccessibility;
@property (readonly) id <XCUIDevice> device;
@property (readonly) id <XCUIRemoteSiriInterface> remoteSiriInterface;
@property (readonly, getter=isEnabled) _Bool enabled;

/* instance methods */
- (id)initWithDevice:(id)device remoteSiriInterface:(id)interface supportsAccessibility:(_Bool)accessibility;
- (void)injectAssistantRecognitionStrings:(id)strings;
- (void)injectVoiceRecognitionAudioInputPaths:(id)paths;
- (_Bool)_usesLegacySiriViewService;
- (id)_siriBundleIdentifier;
- (unsigned long long)_expectedStateForActivate;
- (void)_assertSiriEnabled;
- (void)_waitForActivation;
- (id)forwardingTargetForSelector:(SEL)selector;

@end

#endif /* XCUISiriService_h */
