//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIScreenDataSource_Protocol_h
#define XCUIScreenDataSource_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCUIScreenDataSource <NSObject>

@required

@property (readonly, nonatomic) _Bool supportsHEICImageEncoding;
@property (readonly, nonatomic) _Bool preferScreenshotsOverScreenRecordings;
@property (readonly, nonatomic) _Bool supportsScreenRecording;
@property (readonly, nonatomic) _Bool supportsMultiDeviceScreenRecording;

/* required instance methods */
- (void)requestScreenIdentifiersWithCompletion:(id /* block */)completion;
- (void)requestTraitsForScreenWithIdentifier:(long long)identifier completion:(id /* block */)completion;
- (void)requestScaleForScreenWithIdentifier:(long long)identifier completion:(id /* block */)completion;
- (void)requestBoundsForScreenWithIdentifier:(long long)identifier completion:(id /* block */)completion;
- (void)requestScreenshotWithRequest:(id)request withReply:(id /* block */)reply;
- (void)requestScreenshotAttachmentWithRequest:(id)request withReply:(id /* block */)reply;
- (void)startScreenRecordingWithRequest:(id)request withReply:(id /* block */)reply;
- (void)stopScreenRecordingWithUUID:(id)uuid withReply:(id /* block */)reply;

@optional

@end

#endif /* XCUIScreenDataSource_Protocol_h */
