//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIElementEventTarget_Protocol_h
#define XCUIElementEventTarget_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCUIElementEventTarget <NSObject>

@required

/* required instance methods */
- (_Bool)tapWithError:(id *)error;
- (_Bool)doubleTapWithError:(id *)error;
- (_Bool)tapWithNumberOfTaps:(unsigned long long)taps numberOfTouches:(unsigned long long)touches error:(id *)error;
- (_Bool)twoFingerTapWithError:(id *)error;
- (_Bool)swipeLeftWithError:(id *)error;
- (_Bool)swipeLeftWithVelocity:(double)velocity error:(id *)error;
- (_Bool)swipeRightWithError:(id *)error;
- (_Bool)swipeRightWithVelocity:(double)velocity error:(id *)error;
- (_Bool)swipeUpWithError:(id *)error;
- (_Bool)swipeUpWithVelocity:(double)velocity error:(id *)error;
- (_Bool)swipeDownWithError:(id *)error;
- (_Bool)swipeDownWithVelocity:(double)velocity error:(id *)error;
- (_Bool)hoverWithError:(id *)error;
- (_Bool)clickWithError:(id *)error;
- (_Bool)doubleClickWithError:(id *)error;
- (_Bool)rightClickWithError:(id *)error;

@optional

@end

#endif /* XCUIElementEventTarget_Protocol_h */
