//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIApplicationRegistry_h
#define XCUIApplicationRegistry_h
@import Foundation;
@import UIKit;

#include "XCUIPlatformApplicationServicesProviding-Protocol.h"

@class NSDictionary, NSObject;
@protocol XCUIApplicationRegistryProvider;

@interface XCUIApplicationRegistry : NSObject

@property (copy) NSDictionary *testDependencies;
@property (copy) NSDictionary *userOverrides;
@property (retain) id <XCUIApplicationRegistryProvider> platformProvider;
@property (readonly) id <XCUIPlatformApplicationServicesProviding> platformServicesProvider;

/* instance methods */
- (void)replacePlatformServicesProvider:(id)provider;
- (id)initWithTestDependencies:(id)dependencies userOverrides:(id)overrides platformServicesProvider:(id)provider;
- (id)recordForApplicationWithBundleIdentifier:(id)identifier error:(id *)error;
- (_Bool)testDependencyExistsForApplicationAtURL:(id)url;

@end

#endif /* XCUIApplicationRegistry_h */
