//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIApplicationProcessTracker_Protocol_h
#define XCUIApplicationProcessTracker_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCUIApplicationProcessTracker <NSObject>

@required

/* required instance methods */
- (id)monitoredApplicationWithProcessIdentifier:(int)identifier;
- (id)applicationProcessWithPID:(int)pid;
- (void)setApplicationProcess:(id)process forPID:(int)pid;
- (id)applicationProcessWithToken:(id)token;
- (void)setApplicationProcess:(id)process forToken:(id)token;
- (id)firstFramePresentationResponsiveSignpostExpectationForApplication:(id)application;

@optional

@end

#endif /* XCUIApplicationProcessTracker_Protocol_h */
