//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUILocation_h
#define XCUILocation_h
#import <XCTest/XCUILocation.h>
@import Foundation;
@import UIKit;

@class CLLocation, NSObject, NSString;

@interface XCUILocation (FBXCTestPrivate)


/* instance methods */
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;

@end

#endif /* XCUILocation_h */
