//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIDeviceAutomationModeInterface_Protocol_h
#define XCUIDeviceAutomationModeInterface_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCUIDeviceAutomationModeInterface <NSObject>

@required

@property (readonly) _Bool supportsAutomationMode;

/* required instance methods */
- (_Bool)enableAutomationModeWithError:(id *)error;

@optional

@end

#endif /* XCUIDeviceAutomationModeInterface_Protocol_h */
