//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIAccessibilityInterface_Protocol_h
#define XCUIAccessibilityInterface_Protocol_h
@import Foundation;
@import UIKit;

#include "XCTElementSnapshotAttributeDataSource-Protocol.h"
#include "XCUIAXNotificationHandling-Protocol.h"

@class NSArray, XCAccessibilityElement;

@protocol XCUIAccessibilityInterface <NSObject, XCUIAXNotificationHandling, XCTElementSnapshotAttributeDataSource>

@required

@property double AXTimeout;
@property (readonly) _Bool supportsAnimationsInactiveNotifications;
@property (readonly) NSArray *activeForegroundApplications;
@property (readonly, nonatomic) XCAccessibilityElement *systemApplication;

/* required instance methods */
- (_Bool)isAccessibilitySupported;
- (_Bool)loadAccessibility:(id *)accessibility;
- (_Bool)unloadAccessibility:(id *)accessibility;
- (_Bool)isValidElement:(id)element;
- (id)hitTestElement:(id)element withPoint:(CGPoint)point error:(id *)error;
- (_Bool)performAction:(id)action onElement:(id)element value:(id)value error:(id *)error;
- (void)notifyWhenEventLoopIsIdleForApplication:(id)application reply:(id /* block */)reply;
- (id)requestSnapshotForElement:(id)element attributes:(id)attributes parameters:(id)parameters error:(id *)error;
- (id)runAccessibilityAuditForApplication:(id)application withConfiguration:(id)configuration error:(id *)error;
- (_Bool)setAttribute:(id)attribute value:(id)value element:(id)element outError:(id *)error;
- (id)parameterizedAttribute:(id)attribute forElement:(id)element parameter:(id)parameter error:(id *)error;
- (_Bool)cachedAccessibilityLoadedValueForPID:(int)pid;
- (_Bool)cachedSystemAppIsLoaded;
- (void)notifyOnNextOccurrenceOfUserTestingEvent:(id)event handler:(id /* block */)handler;
- (void)notifyWhenNoAnimationsAreActiveForApplication:(id)application reply:(id /* block */)reply;
- (id)viewDidAppearExpectationForElement:(id)element viewControllerName:(id)name;
- (void)notifyWhenViewControllerViewDidDisappearReply:(id /* block */)reply;
- (_Bool)enableFauxCollectionViewCells:(id *)cells;
- (void)waitForQuiescenceOnAllForegroundApplicationsAsPreEvent:(_Bool)event;
- (id)localizableStringsDataForActiveApplications;
- (void)registerForAXNotificationsForApplicationWithPID:(int)pid timeout:(double)timeout completion:(id /* block */)completion;
- (void)unregisterForAXNotificationsForApplicationWithPID:(int)pid;
- (id)addObserverForAXNotification:(id)axnotification handler:(id /* block */)handler;
- (void)removeObserver:(id)observer forAXNotification:(id)axnotification;
- (void)performWhenMenuOpens:(id)opens block:(id /* block */)block;
- (id)accessibilityElementForElementAtPoint:(CGPoint)point error:(id *)error;

@optional

@end

#endif /* XCUIAccessibilityInterface_Protocol_h */
