//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIKnobControl_h
#define XCUIKnobControl_h
@import Foundation;
@import UIKit;

@class NSObject, XCUIScreen;

@interface XCUIKnobControl : NSObject

@property (readonly, weak) XCUIScreen *screen;

/* instance methods */
- (id)initWithScreen:(id)screen;
- (void)nudgeInDirection:(unsigned long long)direction;
- (void)rotateByNumberOfClicks:(unsigned long long)clicks clockwise:(_Bool)clockwise;
- (void)select;

@end

#endif /* XCUIKnobControl_h */
