//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIElement_h
#define XCUIElement_h
#import <XCTest/XCUIElement.h>
@import Foundation;
@import UIKit;
#import <TargetConditionals.h>

#include "XCTNSPredicateExpectationObject-Protocol.h"
#include "XCUIElementAttributesPrivate-Protocol.h"
#include "XCUIElementEventTarget-Protocol.h"
#include "XCUIElementTypeQueryProvider_Private-Protocol.h"

@class NSObject, NSString, XCElementSnapshot, XCTLocalizableStringInfo, XCUIApplication, XCUICoordinate, XCUIDevice, XCUIElementQuery, XCUIScreen;
@protocol XCUIDevice;

@interface XCUIElement (FBXCTestPrivate)

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly) id <XCUIDevice> device;
@property (readonly, nonatomic) XCUIApplication *application;
@property (readonly) XCUIElementQuery *query;
@property (retain) id/*XCElementSnapshot*/ lastSnapshot;
@property (readonly, copy) NSString *compactDescription;
@property (readonly, copy) XCUIElement *elementBoundByAccessibilityElement;
@property _Bool safeQueryResolutionEnabled;
@property (readonly) long long displayID;
#if !TARGET_OS_TV && !TARGET_OS_WATCH
@property (readonly, nonatomic) UIInterfaceOrientation interfaceOrientation;
#endif
@property (readonly) _Bool hasBannerNotificationIsStickyAttribute;
@property (readonly) _Bool bannerNotificationIsSticky;
@property (readonly) id <XCUIElementEventTarget> eventTarget;
@property (readonly, copy) XCUICoordinate *hitPointCoordinate;
@property (readonly) _Bool isTouchBarElement;
@property (readonly) _Bool isTopLevelTouchBarElement;
@property (readonly) _Bool hasKeyboardFocus;
@property (readonly) XCUIScreen *screen;
@property (readonly) CGRect screenshotFrame;
@property (readonly, copy) XCUIElement *includingNonModalElements;
@property (readonly, copy) XCUIElement *excludingNonModalElements;
@property (readonly) _Bool hasUIInterruptions;
@property (readonly, copy) XCTLocalizableStringInfo *localizableStringInfo;
@property (readonly) NSString *identifier;
@property (readonly) CGRect frame;
@property (readonly) id value;
@property (readonly, copy) NSString *title;
@property (readonly, copy) NSString *label;
@property (readonly, getter=isEnabled) _Bool enabled;
@property (readonly) long long horizontalSizeClass;
@property (readonly) long long verticalSizeClass;
@property (readonly) NSString *placeholderValue;
@property (readonly, getter=isSelected) _Bool selected;
@property (readonly) _Bool hasFocus;
@property (readonly, copy) XCUIElementQuery *bannerNotifications;
@property (readonly, copy) XCUIElementQuery *touchBars;
@property (readonly, copy) XCUIElementQuery *groups;
@property (readonly, copy) XCUIElementQuery *windows;
@property (readonly, copy) XCUIElementQuery *sheets;
@property (readonly, copy) XCUIElementQuery *drawers;
@property (readonly, copy) XCUIElementQuery *alerts;
@property (readonly, copy) XCUIElementQuery *dialogs;
@property (readonly, copy) XCUIElementQuery *buttons;
@property (readonly, copy) XCUIElementQuery *radioButtons;
@property (readonly, copy) XCUIElementQuery *radioGroups;
@property (readonly, copy) XCUIElementQuery *checkBoxes;
@property (readonly, copy) XCUIElementQuery *disclosureTriangles;
@property (readonly, copy) XCUIElementQuery *popUpButtons;
@property (readonly, copy) XCUIElementQuery *comboBoxes;
@property (readonly, copy) XCUIElementQuery *menuButtons;
@property (readonly, copy) XCUIElementQuery *toolbarButtons;
@property (readonly, copy) XCUIElementQuery *popovers;
@property (readonly, copy) XCUIElementQuery *keyboards;
@property (readonly, copy) XCUIElementQuery *keys;
@property (readonly, copy) XCUIElementQuery *navigationBars;
@property (readonly, copy) XCUIElementQuery *tabBars;
@property (readonly, copy) XCUIElementQuery *tabGroups;
@property (readonly, copy) XCUIElementQuery *toolbars;
@property (readonly, copy) XCUIElementQuery *statusBars;
@property (readonly, copy) XCUIElementQuery *tables;
@property (readonly, copy) XCUIElementQuery *tableRows;
@property (readonly, copy) XCUIElementQuery *tableColumns;
@property (readonly, copy) XCUIElementQuery *outlines;
@property (readonly, copy) XCUIElementQuery *outlineRows;
@property (readonly, copy) XCUIElementQuery *disclosedChildRows;
@property (readonly, copy) XCUIElementQuery *browsers;
@property (readonly, copy) XCUIElementQuery *collectionViews;
@property (readonly, copy) XCUIElementQuery *sliders;
@property (readonly, copy) XCUIElementQuery *pageIndicators;
@property (readonly, copy) XCUIElementQuery *progressIndicators;
@property (readonly, copy) XCUIElementQuery *activityIndicators;
@property (readonly, copy) XCUIElementQuery *segmentedControls;
@property (readonly, copy) XCUIElementQuery *pickers;
@property (readonly, copy) XCUIElementQuery *pickerWheels;
@property (readonly, copy) XCUIElementQuery *switches;
@property (readonly, copy) XCUIElementQuery *toggles;
@property (readonly, copy) XCUIElementQuery *links;
@property (readonly, copy) XCUIElementQuery *images;
@property (readonly, copy) XCUIElementQuery *icons;
@property (readonly, copy) XCUIElementQuery *searchFields;
@property (readonly, copy) XCUIElementQuery *scrollViews;
@property (readonly, copy) XCUIElementQuery *scrollBars;
@property (readonly, copy) XCUIElementQuery *staticTexts;
@property (readonly, copy) XCUIElementQuery *textFields;
@property (readonly, copy) XCUIElementQuery *secureTextFields;
@property (readonly, copy) XCUIElementQuery *datePickers;
@property (readonly, copy) XCUIElementQuery *textViews;
@property (readonly, copy) XCUIElementQuery *menus;
@property (readonly, copy) XCUIElementQuery *menuItems;
@property (readonly, copy) XCUIElementQuery *menuBars;
@property (readonly, copy) XCUIElementQuery *menuBarItems;
@property (readonly, copy) XCUIElementQuery *maps;
@property (readonly, copy) XCUIElementQuery *webViews;
@property (readonly, copy) XCUIElementQuery *steppers;
@property (readonly, copy) XCUIElementQuery *incrementArrows;
@property (readonly, copy) XCUIElementQuery *decrementArrows;
@property (readonly, copy) XCUIElementQuery *tabs;
@property (readonly, copy) XCUIElementQuery *timelines;
@property (readonly, copy) XCUIElementQuery *ratingIndicators;
@property (readonly, copy) XCUIElementQuery *valueIndicators;
@property (readonly, copy) XCUIElementQuery *splitGroups;
@property (readonly, copy) XCUIElementQuery *splitters;
@property (readonly, copy) XCUIElementQuery *relevanceIndicators;
@property (readonly, copy) XCUIElementQuery *colorWells;
@property (readonly, copy) XCUIElementQuery *helpTags;
@property (readonly, copy) XCUIElementQuery *mattes;
@property (readonly, copy) XCUIElementQuery *dockItems;
@property (readonly, copy) XCUIElementQuery *rulers;
@property (readonly, copy) XCUIElementQuery *rulerMarkers;
@property (readonly, copy) XCUIElementQuery *grids;
@property (readonly, copy) XCUIElementQuery *levelIndicators;
@property (readonly, copy) XCUIElementQuery *cells;
@property (readonly, copy) XCUIElementQuery *layoutAreas;
@property (readonly, copy) XCUIElementQuery *layoutItems;
@property (readonly, copy) XCUIElementQuery *handles;
@property (readonly, copy) XCUIElementQuery *otherElements;
@property (readonly, copy) XCUIElementQuery *statusItems;
@property (readonly) XCUIElement *firstMatch;

/* class methods */
+ (_Bool)_isInvalidEventDuration:(double)duration;
+ (id)standardAttributeNames;

/* instance methods */
- (void)playBackEventStreamAtURL:(id)url withSpeed:(double)speed;
- (void)clickForDuration:(double)duration;
- (void)tripleClick;
/**
 Public since Xcode 14. Scrolls the element's nearest scrollable ancestor until the element
 becomes visible. It doesn't report failures through an error out-param, so completion is
 verified by re-checking visibility afterwards.
 */
- (void)scrollToVisible;
- (void)tapOrClick;
- (void)forcePress;
- (void)pressWithPressure:(double)pressure duration:(double)duration;
- (id)_normalizedUISliderPositionForSnapshot:(id)snapshot isVertical:(_Bool *)vertical error:(id *)error;
- (id)_iOSSliderAdjustmentEventWithTargetPosition:(double)position snapshot:(id)snapshot error:(id *)error;
- (id)_normalizedSliderPositionForSnapshot:(id)snapshot isVertical:(_Bool *)vertical error:(id *)error;
- (void)hover;
- (void)click;
- (void)doubleClick;
- (void)rightClick;
- (id)_clickElementSnapshot:(id)snapshot forDuration:(double)duration thenDragToElement:(id)element withVelocity:(double)velocity thenHoldFor:(double)_for;
- (id)_hitPointByAttemptingToScrollToVisibleSnapshot:(id)snapshot error:(id *)error;
- (void)tap;
- (void)doubleTap;
- (void)_swipe:(unsigned long long)_swipe withVelocity:(double)velocity;
- (_Bool)_focusValidForElementSnapshot:(id)snapshot error:(id *)error;
- (_Bool)_dispatchEventWithEventBuilder:(id /* block */)builder error:(id *)error;
- (void)_dispatchEvent:(id)event eventBuilder:(id /* block */)builder;
- (_Bool)_shouldDispatchEvent:(id *)event;
- (_Bool)_allUIInterruptionsHandledForElementSnapshot:(id)snapshot error:(id *)error;
- (void)performWithUnderlyingElement:(id /* block */)element;
- (id)snapshotWithError:(id *)error;
- (id)screenshot;
- (id)screenshotWithPreferredEncoding:(id)encoding options:(unsigned long long)options;
- (id)screenshotAttachmentWithPreferredEncoding:(id)encoding options:(unsigned long long)options;
- (id)initWithElementQuery:(id)query;
- (_Bool)existsNoRetry;
- (id)_descendantsMatchingTypes:(id)types;
- (id)_childrenMatchingTypes:(id)types;
- (id)_debugDescriptionWithSnapshot:(id)snapshot noMatchesMessage:(id)message;
- (_Bool)evaluatePredicateForExpectation:(id)expectation debugMessage:(id *)message;
- (_Bool)_waitForExistenceWithTimeout:(double)timeout;
- (id)makeNonExistenceExpectation;
- (_Bool)_waitForNonExistenceWithTimeout:(double)timeout;
- (_Bool)_waitForHittableWithTimeout:(double)timeout;
- (void)resolveOrRaiseTestFailure;
- (_Bool)resolveOrRaiseTestFailure:(_Bool)failure error:(id *)error;
- (void)captureDebugInformation;
- (unsigned long long)traits;
- (_Bool)isHittable;
- (void)handleUIInterruptions;
- (id)valuesForAccessibilityAttributes:(id)attributes error:(id *)error;
- (id)valueForAccessibilityAttribute:(id)attribute error:(id *)error;

@end

#endif /* XCUIElement_h */
