//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIApplicationMonitor_Protocol_h
#define XCUIApplicationMonitor_Protocol_h
@import Foundation;
@import UIKit;

#include "XCUIApplicationPlatformServicesProviderDelegate-Protocol.h"
#include "XCUIApplicationProcessTracker-Protocol.h"
@class NSSet, XCUIApplicationRegistry;

@protocol XCUIApplicationMonitor <NSObject, XCUIApplicationProcessTracker, XCUIApplicationPlatformServicesProviderDelegate>

@required

@property (readonly) _Bool providesClientStateUpdates;
@property (retain) XCUIApplicationRegistry *applicationRegistry;
@property (readonly) NSSet *unsupportedBundleIdentifiersForAutomationSessions;

/* required instance methods */
- (void)replacePlatformServicesProvider:(id)provider;
- (void)resetTrackedAppStates;
- (void)crashInProcessWithBundleID:(id)id path:(id)path pid:(int)pid symbol:(id)symbol;
- (void)stopTrackingProcessWithToken:(id)token;
- (void)processWithToken:(id)token exitedWithStatus:(int)status;
- (id)applicationImplementationForApplicationAtPath:(id)path bundleID:(id)id isTestDependency:(_Bool)dependency;
- (void)terminateApplicationProcess:(id)process withToken:(id)token;
- (void)launchRequestedForApplicationProcess:(id)process;
- (void)terminationTrackedForApplicationProcess:(id)process;
- (void)waitForUnrequestedTerminationOfLaunchedApplicationsWithTimeout:(double)timeout;
- (void)acquireBackgroundAssertionForPID:(int)pid reply:(id /* block */)reply;
- (void)retainApplicationProcessUntilCrashHandlingWithPID:(int)pid;
- (void)resetMonitoredApplicationsForCrashes;

@optional

@end

#endif /* XCUIApplicationMonitor_Protocol_h */
