//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIApplicationAutomationSessionProviding_Protocol_h
#define XCUIApplicationAutomationSessionProviding_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCUIApplicationAutomationSessionProviding <NSObject>

@required

@property (readonly) long long applicationAutomationSessionSupport;

/* required instance methods */
- (void)requestAutomationSessionForTestTargetWithPID:(int)pid preferredBackendPath:(id)path reply:(id /* block */)reply;
- (void)requestUnsupportedBundleIdentifiersForAutomationSessions:(id /* block */)sessions;

@optional

@end

#endif /* XCUIApplicationAutomationSessionProviding_Protocol_h */
