//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIApplicationPlatformServicesProviderDelegate_Protocol_h
#define XCUIApplicationPlatformServicesProviderDelegate_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCUIApplicationPlatformServicesProviderDelegate <NSObject>

@required

/* required instance methods */
- (void)updatedApplicationStateSnapshot:(id)snapshot;
- (void)updatedDeviceOrientation:(long long)orientation;
- (void)updatedInterfaceOrientation:(long long)orientation;

@optional

@end

#endif /* XCUIApplicationPlatformServicesProviderDelegate_Protocol_h */
