//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIButtonConsole_h
#define XCUIButtonConsole_h
@import Foundation;
@import UIKit;

@class NSObject, XCUIScreen;

@interface XCUIButtonConsole : NSObject

@property (readonly, weak) XCUIScreen *screen;

/* instance methods */
- (id)initWithScreen:(id)screen;
- (void)pressButton:(unsigned long long)button;
- (void)pressButton:(unsigned long long)button forDuration:(double)duration;
- (void)_silentlyPressButton:(unsigned long long)button forDuration:(double)duration;

@end

#endif /* XCUIButtonConsole_h */
