//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIAXNotificationHandling_Protocol_h
#define XCUIAXNotificationHandling_Protocol_h
@import Foundation;
@import UIKit;

@protocol XCUIAXNotificationHandling <NSObject>

@required

@property (readonly) _Bool axNotificationsIncludeElement;

/* required instance methods */
- (void)handleAccessibilityNotification:(int)notification fromElement:(id)element payload:(id)payload;

@optional

@end

#endif /* XCUIAXNotificationHandling_Protocol_h */
