//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIHitPointResult_h
#define XCUIHitPointResult_h
@import Foundation;
@import UIKit;

@class NSObject;

@interface XCUIHitPointResult : NSObject

@property (readonly) CGPoint hitPoint;
@property (readonly, getter=isHittable) _Bool hittable;

/* instance methods */
- (id)initWithHitPoint:(CGPoint)point hittable:(_Bool)hittable;
- (id)description;

@end

#endif /* XCUIHitPointResult_h */
