//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIPlatformApplicationServicesProviding_Protocol_h
#define XCUIPlatformApplicationServicesProviding_Protocol_h
@import Foundation;
@import UIKit;

#include "XCUIApplicationPlatformServicesProviderDelegate-Protocol.h"

@protocol XCUIPlatformApplicationServicesProviding <NSObject>

@required

@property (weak) id <XCUIApplicationPlatformServicesProviderDelegate> platformApplicationServicesProviderDelegate;
@property (readonly) _Bool providesClientStateUpdates;

/* required instance methods */
- (void)beginMonitoringApplicationWithSpecifier:(id)specifier;
- (void)launchApplicationWithPath:(id)path bundleID:(id)id arguments:(id)arguments environment:(id)environment completion:(id /* block */)completion;
- (void)terminateApplicationWithBundleID:(id)id pid:(int)pid completion:(id /* block */)completion;
- (void)openDefaultApplicationForURL:(id)url completion:(id /* block */)completion;
- (void)openURL:(id)url usingApplication:(id)application completion:(id /* block */)completion;
- (void)requestApplicationSpecifierForPID:(int)pid reply:(id /* block */)reply;

@optional

@end

#endif /* XCUIPlatformApplicationServicesProviding_Protocol_h */
