//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.534, BuildCommit: b276a7d7daf462beda4afef1c43a753a47405355)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 13, SDK: 26.4, Tool: ld (1267)
//    - LC_SOURCE_VERSION: 24904.0.0.0.0
//
#ifndef XCUIElementQuery_h
#define XCUIElementQuery_h
#import <XCTest/XCUIElementQuery.h>
@import Foundation;
@import UIKit;

#include "XCTElementSnapshotAttributeDataSource-Protocol.h"
#include "XCTElementSnapshotProvider-Protocol.h"
#include "XCUIElementTypeQueryProvider_Private-Protocol.h"

@class NSArray, NSObject, NSOrderedSet, NSSet, NSString, XCElementSnapshot, XCUIApplication, XCUIElement;
@protocol XCTElementSetTransformer;

@interface XCUIElementQuery (FBXCTestPrivate)

@property (readonly) XCUIElementQuery *inputQuery;
@property _Bool changesScope;
@property _Bool stopsOnFirstMatch;
@property (copy) NSSet *expressedTypes;
@property (copy) NSArray *expressedIdentifiers;
@property (copy) NSOrderedSet *lastInput;
@property (copy) NSOrderedSet *lastOutput;
@property _Bool modalViewPruningDisabled;
@property (retain) id/*XCElementSnapshot*/ rootElementSnapshot;
@property (readonly) id <XCTElementSnapshotAttributeDataSource> elementSnapshotAttributeDataSource;
@property (readonly) XCUIApplication *application;
@property (readonly, copy) NSString *queryDescription;
@property (readonly, copy) NSString *elementDescription;
@property (retain) id <XCTElementSetTransformer> transformer;
@property (readonly, copy) NSSet *allExpressedTypes;
@property (readonly, copy) XCUIElementQuery *includingNonModalElements;
@property (readonly, copy) XCUIElementQuery *excludingNonModalElements;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) XCUIElementQuery *bannerNotifications;
@property (readonly, copy) XCUIElementQuery *touchBars;
@property (readonly, copy) XCUIElementQuery *groups;
@property (readonly, copy) XCUIElementQuery *windows;
@property (readonly, copy) XCUIElementQuery *sheets;
@property (readonly, copy) XCUIElementQuery *drawers;
@property (readonly, copy) XCUIElementQuery *alerts;
@property (readonly, copy) XCUIElementQuery *dialogs;
@property (readonly, copy) XCUIElementQuery *buttons;
@property (readonly, copy) XCUIElementQuery *radioButtons;
@property (readonly, copy) XCUIElementQuery *radioGroups;
@property (readonly, copy) XCUIElementQuery *checkBoxes;
@property (readonly, copy) XCUIElementQuery *disclosureTriangles;
@property (readonly, copy) XCUIElementQuery *popUpButtons;
@property (readonly, copy) XCUIElementQuery *comboBoxes;
@property (readonly, copy) XCUIElementQuery *menuButtons;
@property (readonly, copy) XCUIElementQuery *toolbarButtons;
@property (readonly, copy) XCUIElementQuery *popovers;
@property (readonly, copy) XCUIElementQuery *keyboards;
@property (readonly, copy) XCUIElementQuery *keys;
@property (readonly, copy) XCUIElementQuery *navigationBars;
@property (readonly, copy) XCUIElementQuery *tabBars;
@property (readonly, copy) XCUIElementQuery *tabGroups;
@property (readonly, copy) XCUIElementQuery *toolbars;
@property (readonly, copy) XCUIElementQuery *statusBars;
@property (readonly, copy) XCUIElementQuery *tables;
@property (readonly, copy) XCUIElementQuery *tableRows;
@property (readonly, copy) XCUIElementQuery *tableColumns;
@property (readonly, copy) XCUIElementQuery *outlines;
@property (readonly, copy) XCUIElementQuery *outlineRows;
@property (readonly, copy) XCUIElementQuery *disclosedChildRows;
@property (readonly, copy) XCUIElementQuery *browsers;
@property (readonly, copy) XCUIElementQuery *collectionViews;
@property (readonly, copy) XCUIElementQuery *sliders;
@property (readonly, copy) XCUIElementQuery *pageIndicators;
@property (readonly, copy) XCUIElementQuery *progressIndicators;
@property (readonly, copy) XCUIElementQuery *activityIndicators;
@property (readonly, copy) XCUIElementQuery *segmentedControls;
@property (readonly, copy) XCUIElementQuery *pickers;
@property (readonly, copy) XCUIElementQuery *pickerWheels;
@property (readonly, copy) XCUIElementQuery *switches;
@property (readonly, copy) XCUIElementQuery *toggles;
@property (readonly, copy) XCUIElementQuery *links;
@property (readonly, copy) XCUIElementQuery *images;
@property (readonly, copy) XCUIElementQuery *icons;
@property (readonly, copy) XCUIElementQuery *searchFields;
@property (readonly, copy) XCUIElementQuery *scrollViews;
@property (readonly, copy) XCUIElementQuery *scrollBars;
@property (readonly, copy) XCUIElementQuery *staticTexts;
@property (readonly, copy) XCUIElementQuery *textFields;
@property (readonly, copy) XCUIElementQuery *secureTextFields;
@property (readonly, copy) XCUIElementQuery *datePickers;
@property (readonly, copy) XCUIElementQuery *textViews;
@property (readonly, copy) XCUIElementQuery *menus;
@property (readonly, copy) XCUIElementQuery *menuItems;
@property (readonly, copy) XCUIElementQuery *menuBars;
@property (readonly, copy) XCUIElementQuery *menuBarItems;
@property (readonly, copy) XCUIElementQuery *maps;
@property (readonly, copy) XCUIElementQuery *webViews;
@property (readonly, copy) XCUIElementQuery *steppers;
@property (readonly, copy) XCUIElementQuery *incrementArrows;
@property (readonly, copy) XCUIElementQuery *decrementArrows;
@property (readonly, copy) XCUIElementQuery *tabs;
@property (readonly, copy) XCUIElementQuery *timelines;
@property (readonly, copy) XCUIElementQuery *ratingIndicators;
@property (readonly, copy) XCUIElementQuery *valueIndicators;
@property (readonly, copy) XCUIElementQuery *splitGroups;
@property (readonly, copy) XCUIElementQuery *splitters;
@property (readonly, copy) XCUIElementQuery *relevanceIndicators;
@property (readonly, copy) XCUIElementQuery *colorWells;
@property (readonly, copy) XCUIElementQuery *helpTags;
@property (readonly, copy) XCUIElementQuery *mattes;
@property (readonly, copy) XCUIElementQuery *dockItems;
@property (readonly, copy) XCUIElementQuery *rulers;
@property (readonly, copy) XCUIElementQuery *rulerMarkers;
@property (readonly, copy) XCUIElementQuery *grids;
@property (readonly, copy) XCUIElementQuery *levelIndicators;
@property (readonly, copy) XCUIElementQuery *cells;
@property (readonly, copy) XCUIElementQuery *layoutAreas;
@property (readonly, copy) XCUIElementQuery *layoutItems;
@property (readonly, copy) XCUIElementQuery *handles;
@property (readonly, copy) XCUIElementQuery *otherElements;
@property (readonly, copy) XCUIElementQuery *statusItems;
@property (readonly) XCUIElement *firstMatch;

/* instance methods */
- (id)init;
- (id)initWithInputQuery:(id)query queryDescription:(id)description transformer:(id)transformer;
- (id)device;
- (id)_derivedExpressedTypes;
- (id)_derivedExpressedIdentifiers;
- (id)_debugDescriptionWithIndent:(id *)indent rootElementSnapshot:(id)snapshot;
- (id)debugDescriptionWithSnapshot:(id)snapshot;
- (id)_descendantsMatchingPredicate:(id)predicate;
- (id)_descendantsMatchingTypes:(id)types;
- (id)_childrenMatchingTypes:(id)types;
- (id)filter:(id /* block */)filter;
- (id)ascending:(unsigned long long)ascending;
- (id)descending:(unsigned long long)descending;
- (id)sorted:(id /* block */)sorted;
- (id)_queryWithPredicate:(id)predicate description:(id)description;
- (id)_queryWithPredicate:(id)predicate;
- (id)_predicateWithType:(unsigned long long)type identifier:(id)identifier;
- (id)_containingPredicate:(id)predicate queryDescription:(id)description;
- (id)elementAtIndex:(unsigned long long)index;
- (id)elementWithTitle:(id)title;
- (id)elementWithLabel:(id)label;
- (id)elementWithIdentifier:(id)identifier;
- (id)elementWithValue:(id)value;
- (id)elementWithPlaceholderValue:(id)value;
- (id)_descendantMatchingAccessibilityElement:(id)element;
- (id)_elementMatchingAccessibilityElementOfSnapshot:(id)snapshot;
- (id)backingQueryWithError:(id *)error;
- (id)uniqueMatchingSnapshotWithError:(id *)error;
- (id)allMatchingSnapshotsWithError:(id *)error;
- (id)_executeWithError:(id *)error;
- (id)_matchingSnapshotsForRemotelyEvaluatedQuery:(id)query error:(id *)error;
- (id)_matchingSnapshotsForLocallyEvaluatedQuery:(id)query error:(id *)error;
- (id)elementSnapshotForDebugDescriptionWithNoMatchesMessage:(id *)message;
- (_Bool)_resolveRemoteElements:(id)elements inSnapshot:(id)snapshot query:(id)query runtimeIssues:(id *)issues error:(id *)error;
- (id)snapshotForElement:(id)element attributes:(id)attributes parameters:(id)parameters timeoutControls:(id)controls error:(id *)error;

@end

#endif /* XCUIElementQuery_h */
